### ISSUE TITLE
Typo in Github Enterprise service name

### ISSUE THREAD

**Issue by sampathBlam** [getferdi/recipes#100]
**Describe the bug**
The name of the Github Enterprise service seems to be set as 'Github Entreprise'. (Probably because Entreprise is French for Enterprise)

**Expected behavior**
The name of the service should be "Github Enterprise"

**Screenshots**

![image](https://user-images.githubusercontent.com/17728976/79240504-7feec900-7e8f-11ea-8c78-632c624b547e.png)

**Comment by sampathBlam** [comment]
@vantezzen : Does it make sense to modify the name to **Github Enterprise** ? If so, I can work on the same.

**Comment by vantezzen** [comment]
Thank you for reporting this.
Yes, it would be good to rename the service but keeping the typo in the recipe ID (otherwise Ferdi won't detect that it's the same service)

**Comment by sampathBlam** [comment]
@vantezzen : Yeah got that. The documentation on updating helped a lot in understanding that part. 
There is a trickier thing though, w.r.t this. I have tried doing the changes locally following the instructions in the [update documentation](https://github.com/getferdi/recipes/blob/master/docs/updating.md).
Currently the `name` field in package.json seems to be Github Entreprise. When I correct the typo and do a `yarn package` to create an archive, I get an error stating that `name` in package.json contains illegal characters. It is pointing out to the whitespace. Apparently, package.json cannot have whitespace in the `name` field's value - [link](https://github.com/npm/npm/issues/3105). I assume these recipes/packages were created long back and npm had not imposed those restrictions by then. But now, when we try to update recipes, we will be facing this issue. And there are restrictions on using capital case characters as well in the name field. We might have to follow those conventions in the package.json.

**Comment by vantezzen** [comment]
Very weird, I've never experienced this before. Are you trying to execute `yarn package` while being inside `/scripts/recipe_src` instead of being in `/scripts/`? That is the only way I could imagine this happening - yarn shouldn't verify the package.json of a recipe

**Comment by sampathBlam** [comment]
My bad !! yeah. I am inside recipe_src. Seriously great catch !! Thank you.

**Comment by vantezzen** [comment]
Closing as #101 is merged. This fix will be available in the next version of Ferdi.
