### ISSUE TITLE
Google Chat Notification Bubble is broken

### ISSUE THREAD

**Issue by mahadevans87** [getferdi/recipes#102]
**Describe the bug**
The red notification bubble next to the Google Chat Service Icon in the side menu does not show the total number of unread notifications. 

**To Reproduce**
1. Make sure you get a new message in Google Chat
2. Verify the notification bubble which appears on top of Google chat icon in the Ferdi Side bar
4. See error - number of unread notifications are not displayed

**Expected behavior**
On top of the red bubble, the number of unread notifications should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/1255523/79321426-fbe91f80-7f28-11ea-87e7-9bd1523b0beb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version Ferdi 5.4.3

**Comment by vantezzen** [comment]
The class names used in the recipe probably changed. The Hangouts Chat recipe seems to be using compiled class names:

https://github.com/getferdi/recipes/blob/b3bdd87c86c776cb4bb556461df8572e75daf2d9/uncompressed/hangoutschat/webview.js#L3-L5

**Comment by sampathBlam** [comment]
Yes they seem to have changed the class names. 
I find it difficult to understand the meaning of direct and indirect messages for Google Hangouts Chat. 
I assume that 
- direct messages are those that are sent directly to you (in private chats, @mentions in rooms)
- indirect messages are those that are sent in rooms ( without mentioning you). 
Is my understanding correct?

**Comment by vantezzen** [comment]
I'm also not sure about that but that sounds like the behavior I would expect
