### ISSUE TITLE
Add "Jitsi" service

### ISSUE THREAD

**Issue by Nokia808** [getferdi/recipes#104]
Hi. I would like to suggest on you adding very important service which is:

https://jitsi.org

It is fully open source centralized Switzerland video conference service. It is free of charge & need no registration & has web service to be used by browsers with full functionality .......

It will be very useful if you add this service - specially at these days of COVID19 pandemic - to Ferdi. Why peoples use Zoom ?? Jitsi is too much better than Zoom. Jitsi is very secure & private & from this regard no compression between it & Zoom ......

Thanks.

**Comment by kytwb** [comment]
@Nokia808 Thanks for the suggestion!

**Comment by sampathBlam** [comment]
@kytwb : I would like to take this up. Can you please assign it to me?

**Comment by sampathBlam** [comment]
@Nokia808 : Is this the video conference service that you are referring to ? https://meet.jit.si/

**Comment by Nokia808** [comment]
@sampathBlam 
Yes. Isn't was clear ? On the home page https://jitsi.org there is a button at middle & to your right called "See it in Action! Start a Meeting". Just click on this button & it will re-direct you to https://meet.jit.si

Best.

**Comment by kytwb** [comment]
@Nokia808 To each their pace 🙏
