### ISSUE TITLE
Sideways scrolling in Trello does not work

### ISSUE THREAD

**Issue by FeikoJoosten** [getferdi/recipes#110]
**Describe the bug**
Some mice have a sideways scroll wheel. You can use this scroll wheel to move horizontally over the screen. However, this doesn't work with Trello. This does work in the regular browser version.

**To Reproduce**
1. Go to the Trello service
2. Got to a Trello page with a wide array of tasks, or reduce the width of your window so you can get a horizontal scrollbar.
3. Try and scroll using the sideways scroll wheel.
4. Notice Trello doesn't scroll sideways using the scroll wheel.

**Expected behavior**
I would expect Trello to respect the sideways scroll wheel.

**Screenshots**
Sideways scroll wheel: 
![image](https://user-images.githubusercontent.com/10920052/79584394-9e8ed300-80ce-11ea-9340-d945efa4b6ad.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 81.0.4044.113
 - Ferdi version: 5.4.4-beta.3

**Additional context**
N/A

**Comment by vantezzen** [comment]
This is a problem in ElectronJS, not Ferdi directly. I have the same mouse and experience the same issues in VSCode etc., see: https://github.com/electron/electron/issues/20874

**Comment by FeikoJoosten** [comment]
Ah fair enough. Thanks for looking into it though!
