### ISSUE TITLE
Recipes regression in Ferdi v5.5.0-gm

### ISSUE THREAD

**Issue by kytwb** [getferdi/recipes#114]
**Describe the bug**
Following the v5.5.0-gm pre-release (see https://github.com/getferdi/ferdi/issues/536 and https://github.com/getferdi/ferdi/issues/536#issuecomment-616093384), we noticed and received feedback regarding regressions on some recipes. The recipes affected seem to be the one leveraging overrideUserAgent (to remove mentions of Ferdi/Electron in the user agent string).

User agent sent to WhatsApp service with v5.5.0-gm:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.141 Safari/537.36 Ferdi/5.5.0-gm (Electron 8.1.1)`

User agent returned from WhatsApp recipe `overrideUserAgent`:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.141 Safari/537.36 Ferdi/5.5.0-gm`

**Expected behavior**

User agent returned from WhatsApp recipe `overrideUserAgent` should be:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.141 Safari/537.36`

**Screenshots**
<img width="490" alt="Screen Shot 2020-04-19 at 11 30 01 AM" src="https://user-images.githubusercontent.com/412895/79686621-520fd880-8231-11ea-9f08-6d6036a835e3.png">

**Desktop (please complete the following information):**
 - Version v5.5.0-gm

**Comment by vantezzen** [comment]
What do you suggest doing to solve this issue? Replacing all of those with
```JavaScript
return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, '');
```
