### ISSUE TITLE
Incorrect Windows path in Updating.md

### ISSUE THREAD

**Issue by FeikoJoosten** [getferdi/recipes#117]
**Describe the bug**
The path in [Updating.md](https://github.com/getferdi/recipes/blob/master/docs/updating.md) for Windows under chapter 1 is incorrect. This path should also include `Roaming`. This means the full path should be `%appdata%/Roaming/Ferdi/recipes/<recipe id>/`

**To Reproduce**
1. Go to Updating.md
2. Go to chapter 1.
3. Notice the incorrect Windows path.

**Expected behavior**
The correct path should be in the Updating.md description.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
 N/A

**Comment by sampathBlam** [comment]
@FeikoJoosten : In general, I have seen that the `%appdata%` environment variable in windows points to the `AppData/Roaming` folder. That would mean that the documentation is correct. Can you check the same either in windows explorer or cmd?

**Comment by FeikoJoosten** [comment]
Yep, you are correct. I normally navigate to the appdata folder manually. Which brings you one folder up... Typing %appdata% in explorer or cmd does indeed bring you to the roaming folder.
