### ISSUE TITLE
Switch back to the original Telegram from Telegram React?

### ISSUE THREAD

**Issue by lolmaus** [getferdi/recipes#128]
I don't know, why the switch to Telegram React was made. I have not found a single thing that is better in Telegram React.

But it has a few issues, I've ran into two:
— On a window 1050px wide the list of chats collapses and chat names are not visible. 
— It is impossible to mention a user because autocomplete does not work.

How do I switch back to web.telegram.org? Why is there no choice between the two?

**Comment by vantezzen** [comment]
Related: #95. I'd suggest moving the current recipe to "telegram-react" and restoring the telegram recipe.

**Comment by lolmaus** [comment]
СС @kytwb.

**Comment by kytwb** [comment]
@lolmaus Sorry for the inconvenience you experienced with this upgrade 🙏 I originally proceeded for https://github.com/getferdi/ferdi/issues/300 as the context menu was not implemented in the previous Telegram client. Linking to https://github.com/evgeny-nadymov/telegram-react/issues/116 to reference one of the issue you experienced with this new client. I will take a look at reverting and offering this client as a new recipe as per @vantezzen suggestion.

**Comment by lolmaus** [comment]
Thx!

I didn't see lack of right click menu as an issue because all the features that Telegram-React offers were available in original Telegram-Web via left click. 🤷‍♂️

**Comment by kytwb** [comment]
I see; I didn't know, I don't use Telegram that much, so thank you for the clarification 🙏 I will proceed as discussed then.
