### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by acorazza** [getferdi/recipes#134]
Name of the service (e.g. WhatsApp): Notion
URL of the service (e.g. whatsapp.com): Notion.so

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vycoder** [comment]
Hi I'm new here. Just wondering, when will it be released? Will this be on the next update or there's something else I need to do to have it on my list of services?

**Comment by vantezzen** [comment]
Theres currently no roadmap or information when this will be added: We'll have to test the existing recipes and add one that works. For now, you can use the "Custom website" service to add notion instead.

**Comment by vycoder** [comment]
Hi I'm sorry but I found this on the wiki. Notion was listed (second to the last bullet on the screenshot)

![image](https://user-images.githubusercontent.com/11130314/82744502-fd212e00-9dab-11ea-9ccd-fe99246a44e5.png)

If it's just a mistake, can you point me to examples on how to add it?

**Comment by vantezzen** [comment]
As I already mentioned above, you can add Notion to Ferdi using the "Custom website" service

**Comment by vantezzen** [comment]
Notion got added to Ferdi. The service will be shipped with the next version of Ferdi
