### ISSUE TITLE
Google Classroom

### ISSUE THREAD

**Issue by opekope2** [getferdi/recipes#135]
Name of the service: Google Classroom
URL of the service: https://classroom.google.com
(I needed to enter https://classroom.google.com/u/0 to show the sign in page)

**Comment by TanZng** [comment]
WIP! (Work In Progress)
Is "ready" but it have some issues while using dark mode.
You can check it out here 👇🏼
https://github.com/TanZng/ferdi-googleclassroom

**Comment by Nokia808** [comment]
Any progression in this issue? It is important to add this service in this black days when global attacks by COVID19 & global shutdown with currently incoming winter.

**Comment by vantezzen** [comment]
This was just added to the repository. The service will be available in the next update of Ferdi

**Comment by Nokia808** [comment]
Too much thanks for that !!

**Comment by flawnn** [comment]
It disappeared for me, lol
