### ISSUE TITLE
Zimbra

### ISSUE THREAD

**Issue by packermann76** [getferdi/recipes#14]
Name of the recipe: Zimbra
URL of the recipe: https://www.zimbra.com/
Features you want implemented (optional):
 - Although it is quite simple to get Zimbra running by c/p e.g. gmail-recipe and add custom-URL, badge-counter is not working.

**Comment by vantezzen** [comment]
This will be difficult for us to implement as it is a paid service. It looks like you already have some experience so you might want to implement this yourself: You'll need to modify `webview.js` to get the current number of unread messages from the page - e.g. search for an element that displays the number and copy its ID.

**Comment by packermann76** [comment]
There is a community edition ( https://www.zimbra.com/try/zimbra-collaboration-open-source/ ). I understand it is hard to get someone to install, configure and then start to implement. Implemeting this one by myself is far from what I can achieve, I have absolutely no experience in JavaScript or Java. I already tried to fiddle with webview.js, but without any success. To make thinks easier, I could provide you a zimbra-account on my private box, it runs a recent version of Zimbra (8.8.8) as a community edition.

**Comment by vantezzen** [comment]
Sorry, didn't see that. Would you be able to provide the HTML code of the inbox (preferably with 1 or 2 unread mails)? I might be able to implement it from the code alone so you won't have to setup a new account just for this.

**Comment by packermann76** [comment]
The most prominent location would be in the title (inside <head>). With one new mail it looks like this:
<title>Zimbra: Posteingang (1)</title>

No new mails look like this:
<title>Zimbra: Posteingang</title>

This is with locales set to german.

There is also a counter on folder-level, tried to c/p the relevant part:
`<div id="main_Mail-parent-FOLDER"><div id="zt__main_Mail__FOLDER" style="position: static; overflow: visible; display: block;" class="OverviewTree" role="tree" tabindex="0" parentid="zov__main_Mail" aria-labelledby="ztih__main_Mail__FOLDER_textCell" aria-activedescendant="zti__main_Mail__2"><div id="ztih__main_Mail__FOLDER" style="position: static; overflow: hidden; display: block;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="1" aria-labelledby="ztih__main_Mail__FOLDER_textCell" aria-expanded="true"><div class="FirstOverviewHeader overviewHeader" id="ztih__main_Mail__FOLDER_div"><table role="presentation" id="ztih__main_Mail__FOLDER_table"><tbody><tr><td id="ztih__main_Mail__FOLDER_nodeCell" style="height: 16px; width: 16px; min-width: 16px;" nowrap="" align="center"><div class="ImgNodeExpanded"></div></td><td class="imageCell" id="ztih__main_Mail__FOLDER_imageCell" nowrap=""></td><td class="FirstOverviewHeader overviewHeader-Text" id="ztih__main_Mail__FOLDER_textCell" width="100%" nowrap="">Mail-Ordner</td><td class="FirstOverviewHeader overviewHeader-Text FakeAnchor" id="ztih__main_Mail__FOLDER_optCell"><div id="DWT36" style="position: static; overflow: visible;" class="ZButton ZWidget ZHasLeftIcon" role="button" tabindex="0" title="Optionen"><table role="presentation" class="ZWidgetTable ZButtonTable" style="table-layout:auto;"><tbody><tr><td id="DWT36_left_icon" class="ZLeftIcon ZWidgetIcon"><div class="ImgContextMenu"></div></td><td id="DWT36_title" class="ZWidgetTitle"></td><td id="DWT36_right_icon" class="ZRightIcon ZWidgetIcon"></td><td id="DWT36_dropdown" class="ZDropDown"></td></tr></tbody></table></div></td></tr></tbody></table></div><div class="DwtTreeItemLevel1ChildDiv" role="group" aria-labelledby="ztih__main_Mail__FOLDER_div" aria-expanded="true" style="display: block;" aria-hidden="false"><div id="zti__main_Mail__2" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__2_textCell" aria-selected="true"><div class="DwtTreeItem DwtTreeItem-selected" id="zti__main_Mail__2_div"><table role="presentation" id="zti__main_Mail__2_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__2_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__2_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA40lEQVQ4jZ2QzarCMBBG81p5gz5LNnkCIRvBhQsLoUmaNFjRNGDBorgQLty+2XdX179ajf3gbIaZw8wQMhIuOO4Z6xsNFxyn3xO6nw40o9ME7aVFPMfpgu1xi/VhPV3g9g466nRB7OLD4+ROYlWvQDN6JXbxvYxmFHInkW9yLP0Si3KBuZ6DC56+Cc3odVBI8d3wvWSWz9KGQwhommbQ9H/3c72uazDGbvUQArz3ySu+FFRVBe99Ei8Fzjn0fZ+E1noosNbCWouyLGGMgTEGSikopVAUxYAHASGEMMbwDan/+pg/grsgUsdQv0UAAAAASUVORK5CYII=" id="CANVAS_IMG_1" border="0"></td><td class="DwtTreeItem-Text-focused" id="zti__main_Mail__2_textCell" nowrap=""><span style="font-weight:bold">Posteingang (1)</span></td><td class="DwtTreeItem-ExtraImg-focused" id="zti__main_Mail__2_extraCell"><div class="ImgDownArrowSmall"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__5" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__5_textCell" aria-selected="false"><div class="DwtTreeItem" id="zti__main_Mail__5_div"><table role="presentation" id="zti__main_Mail__5_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__5_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__5_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACcElEQVQ4ja3TzU4TcRjF4f8deBNeiUlh70YTr8CNiYs2dKaTQjRVoy3GxGAQWUihiS2UVi0FBijUDp22M/QjlYgKQRCsgEApLR8DP1egwIKY+CZneZ6zeoX4H+f1evk7Qohr/1SORqNEo1EikQiDg4NEIhHOo+cGLgIn5XA4zMDAAKFQiFAoRDAYJBAIEAgE6Ovrw+/309TUxBngfDkYDOL1epEkCafTicPhwOFwYLfbsdvtNDc3nwUURcHlciHLMrIsI0kSiqIwOTmJruskk0kSiQTj4+OoqorNZvsDKIpCuVymVCpRLBbJ5/OYpolhGGQyGTRNI5FIMDY2hqqqDA8PnwVcLhelUolCocDMzAymaZLL5Uin00xPT5NKpVBVFVVVicfjxGKxs4AsyxQKBWLxETq7/bg9PtweH/1DU5em1eO9IyRJOl3OZDLouk7/0BSWZXFylnXE/sEh9cY+1Vqdze0aAG6PDyFJEoZhEI3F6eh6zcP2F4ylTACOj485OLRo7B1Qq++R8feS7vGzVd1ldu4rbZ6nI0KSJLLZLLquo2kaA+G35IqfsKwjxpNpPqQNUrrJ5naNeHcXsVcvqdbqTGfztD3yPRFOpxNd1xmMvMft8aEZZYxCmcbePju7Dbaqu6xvVqmsb7Hy8xdLq+vUG/v09b/j3qP266KlpQVN00gmk0xMTKAZZUqzn9neqZMxS5jFj5jFWZZ/bLC4ssb8UgXLOuJZZ89hq+/5VSGEEDabjRs3b+H2+BhN5pidmz9d/V7Z4NvKGgvLFb4srrKwXKFaq/PA17F14bHejI5e6Q2PcPuudGnk+4/rQgjxGxW0gn55QoT+AAAAAElFTkSuQmCC" id="CANVAS_IMG_2" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__5_textCell" nowrap="">Gesendet</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__5_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__6" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__6_textCell"><div class="DwtTreeItem" id="zti__main_Mail__6_div"><table role="presentation" id="zti__main_Mail__6_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__6_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__6_imageCell" nowrap=""><div class="ImgDraftFolder"></div></td><td class="DwtTreeItem-Text" id="zti__main_Mail__6_textCell" nowrap="">Entwürfe</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__6_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__4" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__4_textCell"><div class="DwtTreeItem" id="zti__main_Mail__4_div"><table role="presentation" id="zti__main_Mail__4_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__4_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__4_imageCell" nowrap=""><div class="ImgSpamFolder"></div></td><td class="DwtTreeItem-Text" id="zti__main_Mail__4_textCell" nowrap="">Spam</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__4_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__3" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__3_textCell"><div class="DwtTreeItem" id="zti__main_Mail__3_div"><table role="presentation" id="zti__main_Mail__3_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__3_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__3_imageCell" nowrap=""><div class="ImgTrash"></div></td><td class="DwtTreeItem-Text" id="zti__main_Mail__3_textCell" nowrap="">Papierkorb</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__3_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div class="vSpace"></div><div id="zti__main_Mail__31866" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__31866_textCell"><div class="DwtTreeItem" id="zti__main_Mail__31866_div"><table role="presentation" id="zti__main_Mail__31866_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__31866_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__31866_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABo0lEQVQ4jbWTWaqrQBCG3ZwnK1Icl9C7CBHRmChkIo7tELVtM0jW898H0YMnXDhcuAX1+H1/VVMtCIIgEELws4XfFiEEQRAgCAL4vo/9fg/f9z+Efw2ZBBO82+3geR5c14XrunAcB7Ztw7ZtWJYFy7Kw2WywXq/x9fUFgRDyATuOA0IINE2DqqpQFAWKokCWZciyDEmSIEkSVqvVKDBNE4ZhQNd16LoOTdNgmiYYY+i6Dowx1HWN2+2GsiyR5znyPIcoihBM08T7/cYwDHi9Xng8Huj7Hn3fo+s6tG2Luq5RVRWKokCe56CUIk3TUWAYBoZhwPP5xP1+R9/34JyjbVs0TTOnlmUJSikopUiSBHEcjwJd12eYcw7OORhjaJpmTp7GzrIMcRwjiiKEYTgKNE2bk6eRm6ZZgJRSZFmGJEkQhiGu1yvO5/O3gHP+sW9VVQs4juMFfDgcvgWMsRmedi6KYgFHUbSAPc8bBaqqLpKnx8qyDGmazmNfLhecTqcZ3m63o0BRFNR1/bHvBE+px+Px40pFURzPWRRF/Ev/+sP91/oD8zpniLGeXKEAAAAASUVORK5CYII=" id="CANVAS_IMG_3" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__31866_textCell" nowrap="">Archiv</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__31866_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__257" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__257_textCell"><div class="DwtTreeItem" id="zti__main_Mail__257_div"><table role="presentation" id="zti__main_Mail__257_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__257_nodeCell" nowrap="" align="center"><div class="ImgNodeCollapsed"></div></td><td style="width:20px" class="imageCell" id="zti__main_Mail__257_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABo0lEQVQ4jbWTWaqrQBCG3ZwnK1Icl9C7CBHRmChkIo7tELVtM0jW898H0YMnXDhcuAX1+H1/VVMtCIIgEELws4XfFiEEQRAgCAL4vo/9fg/f9z+Efw2ZBBO82+3geR5c14XrunAcB7Ztw7ZtWJYFy7Kw2WywXq/x9fUFgRDyATuOA0IINE2DqqpQFAWKokCWZciyDEmSIEkSVqvVKDBNE4ZhQNd16LoOTdNgmiYYY+i6Dowx1HWN2+2GsiyR5znyPIcoihBM08T7/cYwDHi9Xng8Huj7Hn3fo+s6tG2Luq5RVRWKokCe56CUIk3TUWAYBoZhwPP5xP1+R9/34JyjbVs0TTOnlmUJSikopUiSBHEcjwJd12eYcw7OORhjaJpmTp7GzrIMcRwjiiKEYTgKNE2bk6eRm6ZZgJRSZFmGJEkQhiGu1yvO5/O3gHP+sW9VVQs4juMFfDgcvgWMsRmedi6KYgFHUbSAPc8bBaqqLpKnx8qyDGmazmNfLhecTqcZ3m63o0BRFNR1/bHvBE+px+Px40pFURzPWRRF/Ev/+sP91/oD8zpniLGeXKEAAAAASUVORK5CYII=" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__257_textCell" nowrap="">Archives</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__257_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__259" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__259_textCell"><div class="DwtTreeItem" id="zti__main_Mail__259_div"><table role="presentation" id="zti__main_Mail__259_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__259_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__259_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABo0lEQVQ4jbWTWaqrQBCG3ZwnK1Icl9C7CBHRmChkIo7tELVtM0jW898H0YMnXDhcuAX1+H1/VVMtCIIgEELws4XfFiEEQRAgCAL4vo/9fg/f9z+Efw2ZBBO82+3geR5c14XrunAcB7Ztw7ZtWJYFy7Kw2WywXq/x9fUFgRDyATuOA0IINE2DqqpQFAWKokCWZciyDEmSIEkSVqvVKDBNE4ZhQNd16LoOTdNgmiYYY+i6Dowx1HWN2+2GsiyR5znyPIcoihBM08T7/cYwDHi9Xng8Huj7Hn3fo+s6tG2Luq5RVRWKokCe56CUIk3TUWAYBoZhwPP5xP1+R9/34JyjbVs0TTOnlmUJSikopUiSBHEcjwJd12eYcw7OORhjaJpmTp7GzrIMcRwjiiKEYTgKNE2bk6eRm6ZZgJRSZFmGJEkQhiGu1yvO5/O3gHP+sW9VVQs4juMFfDgcvgWMsRmedi6KYgFHUbSAPc8bBaqqLpKnx8qyDGmazmNfLhecTqcZ3m63o0BRFNR1/bHvBE+px+Px40pFURzPWRRF/Ev/+sP91/oD8zpniLGeXKEAAAAASUVORK5CYII=" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__259_textCell" nowrap="">Entwürfe</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__259_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__264" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__264_textCell"><div class="DwtTreeItem" id="zti__main_Mail__264_div"><table role="presentation" id="zti__main_Mail__264_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__264_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__264_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABo0lEQVQ4jbWTWaqrQBCG3ZwnK1Icl9C7CBHRmChkIo7tELVtM0jW898H0YMnXDhcuAX1+H1/VVMtCIIgEELws4XfFiEEQRAgCAL4vo/9fg/f9z+Efw2ZBBO82+3geR5c14XrunAcB7Ztw7ZtWJYFy7Kw2WywXq/x9fUFgRDyATuOA0IINE2DqqpQFAWKokCWZciyDEmSIEkSVqvVKDBNE4ZhQNd16LoOTdNgmiYYY+i6Dowx1HWN2+2GsiyR5znyPIcoihBM08T7/cYwDHi9Xng8Huj7Hn3fo+s6tG2Luq5RVRWKokCe56CUIk3TUWAYBoZhwPP5xP1+R9/34JyjbVs0TTOnlmUJSikopUiSBHEcjwJd12eYcw7OORhjaJpmTp7GzrIMcRwjiiKEYTgKNE2bk6eRm6ZZgJRSZFmGJEkQhiGu1yvO5/O3gHP+sW9VVQs4juMFfDgcvgWMsRmedi6KYgFHUbSAPc8bBaqqLpKnx8qyDGmazmNfLhecTqcZ3m63o0BRFNR1/bHvBE+px+Px40pFURzPWRRF/Ev/+sP91/oD8zpniLGeXKEAAAAASUVORK5CYII=" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__264_textCell" nowrap="">Rechnungen</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__264_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div><div id="zti__main_Mail__6259" style="position: static; overflow: visible;" class="DwtTreeItem-Control" role="treeitem" tabindex="0" aria-level="2" aria-labelledby="zti__main_Mail__6259_textCell"><div class="DwtTreeItem" id="zti__main_Mail__6259_div"><table role="presentation" id="zti__main_Mail__6259_table" style="table-layout:fixed; width:100%"><tbody><tr><td style="width: 16px; height: 16px; min-width: 16px;" id="zti__main_Mail__6259_nodeCell" nowrap="" align="center"></td><td style="width:20px" class="imageCell" id="zti__main_Mail__6259_imageCell" nowrap=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABo0lEQVQ4jbWTWaqrQBCG3ZwnK1Icl9C7CBHRmChkIo7tELVtM0jW898H0YMnXDhcuAX1+H1/VVMtCIIgEELws4XfFiEEQRAgCAL4vo/9fg/f9z+Efw2ZBBO82+3geR5c14XrunAcB7Ztw7ZtWJYFy7Kw2WywXq/x9fUFgRDyATuOA0IINE2DqqpQFAWKokCWZciyDEmSIEkSVqvVKDBNE4ZhQNd16LoOTdNgmiYYY+i6Dowx1HWN2+2GsiyR5znyPIcoihBM08T7/cYwDHi9Xng8Huj7Hn3fo+s6tG2Luq5RVRWKokCe56CUIk3TUWAYBoZhwPP5xP1+R9/34JyjbVs0TTOnlmUJSikopUiSBHEcjwJd12eYcw7OORhjaJpmTp7GzrIMcRwjiiKEYTgKNE2bk6eRm6ZZgJRSZFmGJEkQhiGu1yvO5/O3gHP+sW9VVQs4juMFfDgcvgWMsRmedi6KYgFHUbSAPc8bBaqqLpKnx8qyDGmazmNfLhecTqcZ3m63o0BRFNR1/bHvBE+px+Px40pFURzPWRRF/Ev/+sP91/oD8zpniLGeXKEAAAAASUVORK5CYII=" border="0"></td><td class="DwtTreeItem-Text" id="zti__main_Mail__6259_textCell" nowrap="">Sent Messages</td><td class="DwtTreeItem-ExtraImg" id="zti__main_Mail__6259_extraCell"><div class="ImgBlank_16"></div></td></tr></tbody></table></div></div></div></div><div class="vSpace"></div></div></div>`

**Comment by vantezzen** [comment]
Just added a [Zimbra recipe](https://github.com/getferdi/recipes/tree/master/uncompressed/zimbra) to this repository - could you please test it by adding it as a custom recipe?

**Comment by packermann76** [comment]
Works as it should! Thx a lot!
