### ISSUE TITLE
Jitsi app doesn't work on Ferdi 5.5.0-gm.2

### ISSUE THREAD

**Issue by tristanplouz** [getferdi/recipes#141]
**Describe the bug**
The service doesn't work anymore with Ferdi 5.5.0-gm.2, the screen of the service still gray.

**To Reproduce**
Just try to start the service

**Expected behavior**
The website view is expected

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Linux
 - Version 5.5.0-gm.2

**Additional context**

**Comment by cybermoloch** [comment]
#146 was incomplete; #167 fixes this with the proposed changes as per @sampathBlam.

**Comment by kytwb** [comment]
The fix has been merged and will ship in the next release of Ferdi.
