### ISSUE TITLE
Unable to add Google Voice

### ISSUE THREAD

**Issue by anatolytkach** [getferdi/recipes#143]
I've deleted the Google Voice service, and now I'm unable to add it back. Please, advise.

**Comment by anatolytkach** [comment]
Updated: was able to put it back, but the custom icon still doesn't work

**Comment by kytwb** [comment]
Fixed via getferdi/server@e4a7fcb.

![Screen Shot 2021-12-31 at 2 53 49 PM](https://user-images.githubusercontent.com/412895/147826789-8183591d-6c5e-49aa-ba71-f0a77d6b71ae.png)
![Screen Shot 2021-12-31 at 2 53 19 PM](https://user-images.githubusercontent.com/412895/147826763-23835c4d-98ff-4dfc-acbc-6a193b49aa04.png)
