### ISSUE TITLE
[Recipe Request] Wire 

### ISSUE THREAD

**Issue by jeroenpraat** [getferdi/recipes#144]
Name of the service (e.g. WhatsApp): Wire
URL of the service (e.g. whatsapp.com): https://app.wire.com

GitHub URL to a recipe: I found 2 recipes on Github, but one was empty and the other one only had 3 files (https://github.com/taylorjdawson/franz-wire-recipe).

Features you want implemented (optional):

I can add it as a custom website, but although notification pop-ups (on Ubuntu Linux) are working, the Ferdi systray icon doesn't show if there's a new message. Also when I add the Wire icon (.png), it is not showing on the sidebar (shows an empty space).

**Comment by vantezzen** [comment]
Thank you for this request. We already have a request for wire over at #92
