### ISSUE TITLE
Further enhancement for "Jitsi Meet" on your application !

### ISSUE THREAD

**Issue by Nokia808** [getferdi/recipes#149]
Hi dear developers.

I discover - while trying "jitsi-meet-electron" package (AppImage) a feature I'm sure that you did not add it when you add Jitsi Meet to your application as I requested from you .....

The issue is that: Jitsi is MULTI-INSTANCES ! This mean that every one can build heir/his own Jitsi instance (server) & not obligated to use https://meet.jit.si which is official instance of the developer teams of Jitsi .... For example:

- we have www.infomaniak.com added it's own Jitsi Meet (which working on their own server not related to Jitsi developers team. See the following links on their web site:
https://www.infomaniak.com/en/meet
https://meet.infomaniak.com/?lang=en
The infomaniak own Jitsi Meet may has more capacity than server of https://meet.jit.si because Infomaniak is a big company .....

- other example is disroot.org own Jitsi - see:
https://disroot.org/
https://calls.disroot.org/

I think when you implement Jitsi Meet you considered https://meet.jit.si only, isn't it ?

You should add a feature in setting of Jitsi Meet on Ferdi allow user to change https://meet.jit.si to what she/he wish like for example Infomaniak.com own Jitsi Meet .....

Here is a screenshot from setting of jitsi-meet-electron that I already downloaded it & started to use it just today:
![jitsi-meet-setting](https://user-images.githubusercontent.com/25375330/80833509-32d45c00-8bde-11ea-9e42-75740c24115d.png)

Look to screenshot carefully & you will see a field [Srver URL] contain "https://meet.jit.si" , which is EDITABLE field .....

You can download "jitsi-meet-electron" package from:
https://github.com/jitsi/jitsi-meet-electron/releases

Thank you.

**Comment by cybermoloch** [comment]
PR #167 Fixes this

**Comment by Nokia808** [comment]
@cybermoloch 
Really amazing work ! Thank you too much !

**Comment by kytwb** [comment]
This will be available in the next release of Ferdi.
