### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by keunes** [getferdi/recipes#15]
Name of the recipe: Mastodon
URL of the recipe: https://mastodon.social/about
Features you want implemented (optional):
- Notification, though kind of standard, would be nice.
- For instance selection, it would be great if autocomplete is enabled, using the centrally-maintained [repository of servers](https://joinmastodon.org/#getting-started). If no custom server set, the default server (https://mastodon.social) should be used.
- Nice-to-have would be the ability to set the [layout type](https://blog.joinmastodon.org/2019/06/mastodon-2.9/) right from Ferdi.

**Comment by vantezzen** [comment]
Looks like such a recipe already exists (<https://github.com/sharkpp/franz-recipe-mastodon>) so we can simply add that to the repository.

**Comment by vantezzen** [comment]
Added via 7dd617a

**Comment by vantezzen** [comment]
Looks like the recipe doesn't work with Franz 5 (https://github.com/sharkpp/franz-recipe-mastodon/issues/2). Removing and reopening recipe (cea06d3)

**Comment by keunes** [comment]
Ah, that's too bad. Thanks for testing @vantezzen!

**Comment by vantezzen** [comment]
This recipe has been added via d003cb9.

**Comment by keunes** [comment]
Hi @vantezzen
I just reinstalled Ferdi and added the Mastodon service, but I didn't recognise the icon. Shouldn't `Logotype (Simple).svg` from the [Mastodon's Press Kit](https://joinmastodon.org/press-kit.zip) be used? Also, Mastodon is the only recipe (of the ones I have) that seems stuck in the Loading phase (let me know if I should create a separate issue for that).

**Comment by vantezzen** [comment]
@keunes Looks like the recipe used a wrong logo there - changed that via cec5721.
I cannot reproduce your issue with Mastodon being stuck on loading - I don't use Mastodon but trying to add "https://mstdn.social/" seems to work fine.
