### ISSUE TITLE
[Recipe Request] Signal

### ISSUE THREAD

**Issue by Rubylion** [getferdi/recipes#159]
Name of the service : Signal Desktop
URL of the service : https://github.com/signalapp/Signal-Desktop

GitHub URL to a recipe : https://github.com/lukasholzer/signal-franz-plugin

**Comment by vantezzen** [comment]
Duplicate of:
getferdi/ferdi#444
getferdi/ferdi#342
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.
The recipe you linked is not valid as it is just an empty repository.
