### ISSUE TITLE
[Recipe Update Request] Mailbox.org

### ISSUE THREAD

**Issue by keunes** [getferdi/recipes#16]
Name of the recipe: Mailbox.org
URL of the recipe: https://mailbox.org/en/
To update: they have a new logo which should be reflected (in order of my estimation of usability):
https://mailbox.org/files/layout/apple-touch-icon-180x180.png
https://mailbox.org/files/layout/logo.svg
https://mailbox.org/files/downloads/Logo_mailbox_org_RGB.jpg (via https://mailbox.org/en/press)

**Comment by vantezzen** [comment]
To also benefit Franz's users I would suggest creating an issue or - even better - a PR to [the recipe repository itself](https://github.com/jonhil/recipe-franz-mailbox.org).

**Comment by keunes** [comment]
Ah, thanks. I've send a request to the Mailbox.org helpdesk to ask for the necessary graphics - when I'll hear back from them I'll create a ticket or PR.

**Comment by keunes** [comment]
@vantezzen The new icon was merged in the recipe. Anything you need to do to get it in Ferdi also?

**Comment by vantezzen** [comment]
Yes, you'll need to import the new recipe using the [GitHub importer script](https://github.com/getferdi/recipes#importing-recipes-from-github). Please note that the original recipe will need to bump their version number as Ferdi won't update otherwise.

**Comment by keunes** [comment]
@vantezzen I can't code so I wouldn't be of any use. With 'you' do you refer to the Ferdi project maintainer(s), or to the recipe maintainer?

**Comment by vantezzen** [comment]
I'll update Ferdi's recipe repository once your PR is trough.

**Comment by vantezzen** [comment]
Updated the recipe repository now that the PR is merged.

**Comment by keunes** [comment]
thanks @vantezzen! Would I need to do anything, to get it on my device? Remove & re-add the service?

**Comment by vantezzen** [comment]
As the recipe repository is a local part of Ferdi you'll have to wait until the next update of Ferdi which will ship the new recipe - Ferdi should update the service automatically after that.
