### ISSUE TITLE
Monica

### ISSUE THREAD

**Issue by keunes** [getferdi/recipes#17]
Name of the recipe: Monica
URL of the recipe: https://app.monicahq.com
Features you want implemented (optional):
- Notification, though kind of standard, would be nice.
- For instance selection, it would be great if autocomplete is enabled, using the centrally-maintained repository of servers. If no custom server set, the default server (https://mastodon.social) should be used.

**Comment by vantezzen** [comment]
It looks like a Monica recipe already exists (<https://github.com/jkbecker/recipe-monica>) but currently has no notification support. If you want to, you can create an issue or PR on that repository so we can simply add that.

**Comment by keunes** [comment]
> It looks like a Monica recipe already exists (https://github.com/jkbecker/recipe-monica) but currently has no notification support.

Ah, thanks for finding that! Is notification support kind of a requirement to include it in the central (Ferdi/Franz) repository? I'll create a ticket against the recipe.

**Comment by vantezzen** [comment]
It is not a requirement but without any special service-specific features like notification support you could also simply use the "Custom Website" recipe instead.

**Comment by keunes** [comment]
ah, and a new feature was discovered, thanks ^^

**Comment by vantezzen** [comment]
Added recipe now nonetheless - we can still update it as soon as there are features added.
Recipe will be available in the next update of Ferdi.
