### ISSUE TITLE
[Recipe Request] Add Yahoo mail

### ISSUE THREAD

**Issue by Nokia808** [getferdi/recipes#178]
I noticed that Yahoo mail not on your list, though your application span extend to cover email services also ... So, why not adding Yahoo mail ?

**Comment by vraravam** [comment]
I am also searching for the same (recipe for Yahoo mail). With the latest ferdi nightly (Version 5.5.1-nightly.16 (5.5.1-nightly.16.2298)) - yahoomail needs a custom user-agent for the new mail (ie not classic) to work.

**Comment by reysantana** [comment]
Hello
Is there any way to add yahoo mail box?
I really need it!

**Comment by vraravam** [comment]
Please see this recipe that I just created: https://github.com/vraravam/franz-recipe-yahoo-mail

**Comment by vantezzen** [comment]
Added via #310
