### ISSUE TITLE
[Recipe Request] ADD SIGNAL

### ISSUE THREAD

**Issue by GuillaumeSorel** [getferdi/recipes#185]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vantezzen** [comment]
Duplicate of:
getferdi/ferdi#444
getferdi/ferdi#342
getferdi/recipes#159
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.
