### ISSUE TITLE
[Recipe Request] Reddit Chat.

### ISSUE THREAD

**Issue by djshadowxm82** [getferdi/recipes#2]
Name of the recipe: Reddit Chat
URL of the recipe: https://github.com/djshadowxm82/recipe-redditchat
Features you want implemented (optional):
 -

**Comment by vantezzen** [comment]
Why do you need [webview.js Lines 3-9](https://github.com/djshadowxm82/recipe-redditchat/blob/master/webview.js#L3-L9)? It doesn't look like you actually use any of the variables set there?

After fixing that you can add your recipe to this repo as described [in the README](https://github.com/getferdi/recipes#adding-your-own-recipes). The recipe request issue template is meant to be used by users who cannot program the recipe themselves and only want to request others to implement it.

**Comment by djshadowxm82** [comment]
Thanks Made the PR you can close this.
