### ISSUE TITLE
Formation of malformed archives when cloning from GitHub

### ISSUE THREAD

**Issue by kittywhiskers** [getferdi/recipes#203]
**Describe the bug**

When attempting to add a recipe from a GitHub repository on macOS 10.15.5 (using `npm run github [repo_url]` in `scripts`), some tarballs generated in `archives` have an unexpected end, resulting in archive corruption (and therefore build failure)

During the build process, it often results into this:
```
Error while verifying recipe: { Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:164:17) errno: -5, code: 'Z_BUF_ERROR' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

```
$ git clone https://github.com/getferdi/recipes
$ cd recipes/scripts
$ npm install
$ npm run github [repository_url]

[removed]
✅ Successfully packaged and added new recipe "[name]"
[Info] Deleting temporarydownloaded repository
[Info] Moving back 'recipe_src_tmp' to 'recipe_src'
✅ Successfully packaged the recipe from your GitHub repository
```
**Expected behavior**

The generation of a valid `.tar.gz` archive in `archives/`

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Repo Latest Commit: https://github.com/getferdi/recipes/commit/f3fa2c5b3726592be36d161afff2c2343a107f58

**Comment by mhatvan** [comment]
Hey @kittywhiskers, can you still reproduce this with the latest master?

**Comment by vraravam** [comment]
In fact, I have never come across this invocation: `npm run github <repoUrl>` till date. Is that documented somewhere?

**Comment by kittywhiskers** [comment]
@mhatvan, great news! https://github.com/getferdi/recipes/pull/292 renders this issue no longer relevant 🎉 

> In fact, I have never come across this invocation: npm run github <repoUrl> till date. Is that documented somewhere?

It used to be a script back when Ferdi used tarballs, it was introduced in https://github.com/getferdi/recipes/commit/e57a73a11fb100baba065daae82d04f4f4d63610 and removed with  #292

Wish all of y'all a great day!
