### ISSUE TITLE
[Recipe Request] SPOTIFY

### ISSUE THREAD

**Issue by andreclemente** [getferdi/recipes#205]
Name of the service: Spotify 
URL of the service: https://open.spotify.com/

GitHub URL to a recipe: https://github.com/ktawaststjerna/recipe-spotify

**Comment by vantezzen** [comment]
Unfortunately, we can't add Spotify as the service requires a [Widevine DRM Certificate](https://en.wikipedia.org/wiki/Widevine) which is only given to large corporations like Google or Microsoft.
