### ISSUE TITLE
Dingtalk

### ISSUE THREAD

**Issue by YuHengKit** [getferdi/recipes#211]
Name of the service (e.g. WhatsApp): Dingtalk
URL of the service (e.g. whatsapp.com):https://www.dingtalk.com/en

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- Notification

**Comment by mhatvan** [comment]
Dingtalk was added to Ferdi recently in: https://github.com/getferdi/recipes/pull/686
