### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by tejaskzwt1** [getferdi/recipes#214]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
I found one recipe here: https://github.com/BallisticPain/franz-recipe-gitlab
can this be incorporated into Ferdi out of the box?

**Comment by kytwb** [comment]
Added via https://github.com/getferdi/recipes/pull/201.

**Comment by manuelnucci** [comment]
Is it just me or GitLab keeps crashing Ferdi waiting in the "Verify browser..." loop?

**Comment by vraravam** [comment]
I have not had that problem @manuelnucci - I'm running the `v5.6.0-nightly.13` version of Ferdi with this recipe without any issues.
