### ISSUE TITLE
[Recipe Request] Tutanota

### ISSUE THREAD

**Issue by D3SOX** [getferdi/recipes#219]
Name of the service: Tutanota
URL of the service: https://mail.tutanota.com/

GitHub URL to a recipe: https://github.com/hichamelkaddioui/franz-recipe-tutanota

Features you want implemented (optional):

- Notification support

**Comment by gustavohellwig** [comment]
good idea. +1

**Comment by Nokia808** [comment]
This is already done ! See this https://github.com/getferdi/recipes/pull/201

**Comment by gustavohellwig** [comment]
How to add that? I can't see in the list:

![Screen Shot 2020-07-13 at 11 41 00](https://user-images.githubusercontent.com/7680647/87283241-c50db000-c4fd-11ea-86b8-344338f33158.png)

**Comment by vantezzen** [comment]
@gustavohellwig The service is currently only available in the latest beta version (5.6.0-beta.2)
