### ISSUE TITLE
Workplace Team URL should be [team].workplace.com, not [team].facebook.com

### ISSUE THREAD

**Issue by OnePinkSheep** [getferdi/recipes#226]
**Describe the bug**
Workspace Team URLs are now [team].workplace.com, but Ferdi still uses [team].facebook.com. As a result, you can't add Workplace to Ferdi.

**To Reproduce**
1. Open Ferdi. 
2. Click on Add New Service.
3. Search for Workplace, and add it.
4. Note that the Team URL still uses facebook.com instead of workplace.com. 

**Expected behavior**
The URL should use the workplace.com domain.

**Screenshots**
![Screenshot of Workplace in Ferdi](https://i.imgur.com/RD0oC8m.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: Ferdi 5.5.0

**Additional context**
The Workplace recipe for Franz uses the new workplace.com domain URL: https://github.com/rherwig/franz-5-workplace

**Comment by navhaxs** [comment]
This has already been fixed in master of this repo, so guessing this issue will get resolved in the next Ferdi app release :)

https://github.com/getferdi/recipes/commit/57fffb6572dd4fa8257357b42448cd2bbeb8d586#diff-ee7f57a0beb3f6f45e3f9cca6bfa9f90
