### ISSUE TITLE
[Recipe Request] Wrike

### ISSUE THREAD

**Issue by vcuculo** [getferdi/recipes#23]
Name of the recipe: Wrike
URL of the recipe: https://www.wrike.com/
Features you want implemented (optional):

**Comment by vcuculo** [comment]
Looks like a Wrike recipe already exists https://github.com/koma-private/recipe-wrike

**Comment by vantezzen** [comment]
Have you tested the recipe you linked? If yes, I would add it to the repository.

**Comment by vantezzen** [comment]
Recipe added. It will be available in the next update of Ferdi.
