### ISSUE TITLE
Proton mail icon is half-invisible in dark mode

### ISSUE THREAD

**Issue by orblazer** [getferdi/recipes#231]
**Describe the bug**
Proton mail icon is half-invisible in dark mode.

**To Reproduce**
1. Enable dark mode.
2. Add a Proton-mail tab.
3. Look at the icon.

**Expected behavior**
A full-contrast Proton mail icon visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/1344792/86905243-15f26280-c112-11ea-9308-2493db272c76.png)

**Additional context**
I think for easy fix that for all application its to add an possibility to have different icon between light and dark mode

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/recipes/issues/204.
