### ISSUE TITLE
[Recipe Request] LINE Messenger SERVICE

### ISSUE THREAD

**Issue by Druwy** [getferdi/recipes#255]
LINE Messenger
https://line.me/en/

**Comment by Druwy** [comment]
This is the main instant messaging app in South-East Asia and Japan where neither WhatsApp nor WeChat are commonly used.

**Comment by vantezzen** [comment]
Thank you for requesting this. Unfortunately, LINE doesn't offer a web version of its messenger so we can't add it to Ferdi.

Duplicate of:
- #213
- #212 
- #33
- #28
