### ISSUE TITLE
Missing Messengers: Signal, Wire, Hoccer

### ISSUE THREAD

**Issue by dstockinger** [getferdi/recipes#26]
**Is your feature request related to a problem? Please describe.**
I need to use multiple additional apps for messengers, which are not yet supported.

**Describe the solution you'd like**
I would like also to use Signal, Wire and Hoccer messengers. Then Ferdi would be the only one single software I need!

**Describe alternatives you've considered**
Not using Ferdi.

**Comment by dstockinger** [comment]
Ok, taking alternative (for the moment). Definitely needs more dev time to provide more functionality than a browser with several open tabs.

**Comment by vantezzen** [comment]
Signal and Hoccer can't be added as they don't provide web clients.
Out of interest, what alternative are you switching to? Pretty much all other alternatives (Franz, Rambox, Station, etc.) use the same concept. There are other apps that don't use webviews (e.g. Volt), but they only offer very few available messengers (e.g. Volt currently only supports Slack, Skype and GMail).
Ferdi's advantage to a normal webbrowser is that it handles notifications of services and shows you which service has how many notifications.

**Comment by dstockinger** [comment]
Thank you for your fast and valuable answer!

I will have open tabs in my browsers and use Android apps for the rest (together with a Pebble smart watch), that's the "alternative" for the moment.
The advantage to see the amount of messages in Ferdi is nice, but - since I had an "insecure browser" error while trying to log into my GMail account - not enough for me to use Ferdi.

Best greetings from Austria,

Dietmar
