### ISSUE TITLE
Rename Riot to Element

### ISSUE THREAD

**Issue by twenster** [getferdi/recipes#269]
**Describe the bug**
As of 15 July 2020, Riot has been rebranded as Element. https://element.io/blog/welcome-to-element/

**To Reproduce**
Add a new Service
Search for Element or browse for Element

**Expected behavior**
searching for Element should return the Element recipe

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser : Ferdi 
 - Version Version 5.5.0 (5.5.0.2116)

**Comment by kytwb** [comment]
It has been done via https://github.com/getferdi/recipes/pull/235 and is pending a new release. Thanks for your patience!
