### ISSUE TITLE
[Recipe Request] Yahoo mail recipe

### ISSUE THREAD

**Issue by vraravam** [getferdi/recipes#273]
Name of the service (e.g. WhatsApp): Yahoo Mail
URL of the service (e.g. whatsapp.com): mail.yahoo.com

GitHub URL to a recipe : https://github.com/vraravam/franz-recipe-yahoo-mail

**Comment by vraravam** [comment]
ping - can someone please review/merge this PR?

**Comment by vraravam** [comment]
Its been more than a month - can someone please review/accept this PR?

**Comment by vantezzen** [comment]
@vraravam Which PR? We already merged all PRs to our recipe repository.

**Comment by vraravam** [comment]
@vantezzen - according to some documentation, I followed and created a recipe for yahoo mail (as present in the description of the original comment). I have also put it under the appropriate license.

Is there some other process for creating a recipe?

**Comment by vantezzen** [comment]
Thank you for taking the time in developing a recipe for Ferdi.

You've now created the recipe, but you'll also need to add it to the recipe repository. Basically, you'll just need to add the recipe file to this repository's `recipes/` folder. You can find our guide on publishing recipes to Ferdi at https://github.com/getferdi/recipes/blob/master/docs/integration.md#publishing

**Comment by vraravam** [comment]
tx @vantezzen - i will follow that now...

**Comment by vraravam** [comment]
Done - have created a PR: https://github.com/getferdi/recipes/pull/310

**Comment by vantezzen** [comment]
Added via #310
