### ISSUE TITLE
cannot add "https://contacts.google.com/" as Custom Website server.

### ISSUE THREAD

**Issue by Nishan-Vivek** [getferdi/recipes#274]
**Describe the bug**
When going to add https://contacts.google.com as a custom website the "Could not validate Custom Website server" error is shown. 

**To Reproduce**
1. Go to  settings -> Available services -> all services
2. Click on 'Custom Website'
3. Enter https://contacts.google.com/  in field "Custom server" then click "Save service"

**Expected behavior**
contacts.google.com saved as custom website

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Ferdi 5.6.0-beta.2

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/276.
