### ISSUE TITLE
[Recipe Request] Bitbucket

### ISSUE THREAD

**Issue by hdhnl** [getferdi/recipes#277]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by hdhnl** [comment]
and also GitLab

**Comment by arioki1** [comment]
gitlab and Bitbucket have been added, gitlab and Bitbucket have been added
