### ISSUE TITLE
Unread messages icon not displayed for Element and Gitter

### ISSUE THREAD

**Issue by D4N** [getferdi/recipes#286]
**Bug description:**

I have added a Riot and Gitter service, but unfortunately neither of which displays the icon that new messages are available.

**Steps to reproduce:**

1. Create a new Gitter and/or Riot service (I have used element.io as the homeserver)
2. Receive a message on either of the services
3. No unread notifications icon/badge is displayed right next to the 

**Expected behavior**

The Element & Gitter icon should also display unread notifications as other services (like slack, discord, telegram and rocket.chat) do.

**Screenshots**
unread icon visible for Rocket.chat, but not for Riot/Element:
![ferdi](https://user-images.githubusercontent.com/786021/92372413-2c5e6f80-f0fd-11ea-9718-8647f64066c5.png)

**Environment:**

- Operating System: opensuse Tumbleweed
- Ferdi Version: 5.5.0 (via flathub)
- Server: Using without an account

- Debug information:
sorry cannot share these, the log contains confidential information

**Comment by awunder** [comment]
fwiw since rocket chat 3.9 those labels wont be shown as well now

**Comment by awunder** [comment]
for rocket see https://github.com/meetfranz/recipe-rocketchat/issues/4 for a fix

**Comment by mhatvan** [comment]
Hey guys, can you still reproduce this with the latest release: https://github.com/getferdi/ferdi/releases/tag/v5.6.1

I use Rocket Chat and Gitter daily and they work as expected, Element I am unable to test.

**Comment by n-st** [comment]
@mhatvan Yes, still no unread icon for Element on 5.6.1.

**Comment by conny3496** [comment]
@mhatvan Yes, the problem still exists in 5.6.1 (on macOS Big Sur 11.5.2.) Element.
Interestingly enough I am getting an unread counter <img width="60" alt="Bildschirmfoto 2021-09-13 um 10 42 49" src="https://user-images.githubusercontent.com/70640137/133055178-674f05c6-045d-4c76-9db8-6ffe7f32bbed.png"> in cases where I am getting a message in an 1-to-1 chat.
In cases where there is a message in a room with multiple people (regardless me being mentioned or not) I do not get an unread counter.
I am always getting a banner notification though.

**Comment by ggogel** [comment]
I upgraded from an older version of Ferdi to version 5.6.3. I believe the old version was 5.5.0, but I'm not sure. I was simply using a custom website for Element and notifications always worked. After the upgrade, both with the custom website and Element recipe, they stopped working.
