### ISSUE TITLE
[Recipe Request] SERVICE

### ISSUE THREAD

**Issue by turkishdrillpress** [getferdi/recipes#291]
Name of the service Grammarly
URL of the service (e.g. whatsapp.com): grammarly.com/

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- Need to be able to use Grammarly inside some of my services to double-check my spelling and grammar. Having Grammarly work within my services is very important. I don't want to have to cut and paste my work into Grammarly and then cut and paste it again within Ferdi once it has been checked

**Comment by vantezzen** [comment]
Duplicate of #284
