### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by cgarst** [getferdi/recipes#294]
Name of the service (e.g. WhatsApp): Office 365
URL of the service (e.g. whatsapp.com): https://www.office.com/login

GitHub URL to a recipe : None found

Features you want implemented (optional):
- Most of the links should continue to open in external programs or web browser.

**Comment by bhanquier** [comment]
I was going to ask for OneDrive but actually Office 365 is a better option, so I support the motion.
Cheers.

**Comment by mhatvan** [comment]
Office 365 is already present in Ferdi: https://github.com/getferdi/recipes/blob/master/recipes/office365-owa/package.json
