### ISSUE TITLE
[Recipe Request] Line

### ISSUE THREAD

**Issue by CyrilleGosset** [getferdi/recipes#296]
Name of the service (e.g. WhatsApp): Line
URL of the service (e.g. whatsapp.com): https://line.me/en/

GitHub URL to a recipe : NA. But the app is available on the chrome webstore: https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc?utm_source=chrome-ntp-icon

Features you want implemented (optional):

-

**Comment by vantezzen** [comment]
Line doesn't seem to offer a web app - only web extension - thus we can't add it to Ferdi, sorry.
