### ISSUE TITLE
[Recipe Request] Notion

### ISSUE THREAD

**Issue by YoannBureauP** [getferdi/recipes#300]
Name of the service (e.g. WhatsApp): Notion
URL of the service (e.g. whatsapp.com): https://www.notion.so/

Features you want implemented (optional): Notification support

**Comment by Nokia808** [comment]
This is already requested at https://github.com/getferdi/recipes/issues/134
So, it is a duplicate of already mentioned request.

@YoannBureauP kindly close this.
