### ISSUE TITLE
[Recipe Request] Simplenote

### ISSUE THREAD

**Issue by ptheriau** [getferdi/recipes#303]
Name of the service (e.g. WhatsApp): Simplenote
URL of the service (e.g. whatsapp.com): https://app.simplenote.com/

GitHub URL to a recipe: https://github.com/ducce/recipe-franz-simplenote

Features you want implemented (optional):

**Comment by arioki1** [comment]
I have created a PR for this issue https://github.com/getferdi/recipes/pull/317
