### ISSUE TITLE
[Recipe Request] Pinterest

### ISSUE THREAD

**Issue by rickvargo** [getferdi/recipes#304]
Name of the service (e.g. WhatsApp): Pinterest
URL of the service (e.g. whatsapp.com): https://www.pinterest.com

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- 
Notification Support & Dark mode support

**Comment by arioki1** [comment]
I have created a PR for this issue https://github.com/getferdi/recipes/pull/316

**Comment by rickvargo** [comment]
Thank you!

Rick

**Comment by arioki1** [comment]
Please close this problem because my pr has been approved
@rickvargo
