### ISSUE TITLE
Tinder

### ISSUE THREAD

**Issue by tr1p0p** [getferdi/recipes#331]
Name of the service (e.g. WhatsApp): Tinder
URL of the service (e.g. whatsapp.com): tinder.com

GitHub URL to a recipe : https://github.com/samuelthomps0n/franz-tinder

Features you want implemented (optional):

- LOCATION (for obvious reasons)

**Comment by mhatvan** [comment]
Tinder was added to Ferdi in: https://github.com/getferdi/recipes/pull/641
