### ISSUE TITLE
Custom Service: How To Open External URLs in Browser

### ISSUE THREAD

**Issue by nullket** [getferdi/recipes#332]
Hello,

I am trying to integrate a custom hosted (company) Outlook Web APP (OWA) from 2016 . So it is not Office365 or the modern OWA. I was able to get the service running but I am having an issue with external URLs. 

Whenever I click on an (external pointing) url in my mails, a new small ferdi windows opens and loads the Webpage. I would like to have it open in my regular browser. Right Clicking and selecting "open Link" does work as desired, the page loads in my browser.  

So far I have nothing special in my index.js, but i suspect there might be a function that could help?

**Comment by nullket** [comment]
It seems like this works without any issue in the current nightlies. I assume this is a electron version issue but I am note sure. Anyway, I close this as it will be available in future releases and those who can not wait (like me) can use the nightlies at their risk.

**Comment by kytwb** [comment]
@nullket thanks for taking the time to check against the nightlies!

**Comment by nullket** [comment]
@kytwb thanks for closing, I simply clicked the wrong button. 

But, further testing showed something odd:

While external urls work fine in the nightly, I am no longer able to download an attachment. When I click on the "download" button for the attachment, the following happens:

**Behaviour in 5.5.0** 
- A new empty (blank) window of ferdi opens, which has the titel  "_self" (not desired)
- The OS file dialog opens asking where to save the attachment (desired)

**Behaviour in 5.6.0-nightly.9 - Without an active session to the mail website in my browser in another tab** 
- External browser opens with login page of mail provider
- After entering the credentials, I get an JSON error page (from my mail provider)

**Behaviour in 5.6.0-nightly.9 -  With an active session to the mail website in my browser in another tab** 
- External browser opens a blank page
  - Url of this page has this scheme `https://mail.mycompany.de/owa/service.svc/s/GetFileAttachment?id=.....`
  - Note the `serviceUrl` in the `package.json` is defined as follows `https://mail.mycompany.de/owa`
- External browser aks to download a file

So this feature got broken with the newest dev versions. Can we reopen this issue or should I file a new one?
