### ISSUE TITLE
Todoist Recipe - Sidebar badges are not working

### ISSUE THREAD

**Issue by rvisharma** [getferdi/recipes#333]
**Describe the bug**
Todoist recipe is using old selectors to get the badge count, causing no badge to be displayed in sidebar

**To Reproduce**
1. Activate Todoist
2. See the Inbox and Today count in todoist's side bar 
3. See error in the Ferdi's side bar - count should be visible

**Expected behavior**
Count should be visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rvisharma** [comment]
#334 PR raised

**Comment by alejandrorascovan** [comment]
This is still an issue for me on 5.6.0 on Mac OS

**Comment by vraravam** [comment]
@alejandrorascovan - looks like the css selector for Todoist might have changed (my suspicion). Unfortunately, I don't use this service - to be able to help debug/solve the changes. If you can raise a PR, I will gladly merge it in.
