### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by minullamahewage** [getferdi/recipes#339]
Name of the service (e.g. WhatsApp): Gitlab
URL of the service (e.g. whatsapp.com):gitlab.com

GitHub URL to a recipe : https://github.com/rogeriopradoj/gitlab-plugin-franz

**Comment by marcolussetti** [comment]
I see at gitlab recipe already present: https://github.com/getferdi/recipes/tree/master/recipes/gitlab . Is there a problem with the existing one?

**Comment by kytwb** [comment]
Duplicate of https://github.com/getferdi/recipes/issues/214, added via https://github.com/getferdi/recipes/pull/201.
