### ISSUE TITLE
Office 365 OWA recipe not showing notifications

### ISSUE THREAD

**Issue by sparker2000** [getferdi/recipes#34]
**Describe the bug**
When you install the office365-owa recipe, new emails will not trigger the the badge notifications.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Additional context**
I was able to fix this issue for my Ferdi by updating webview.js.
From:
`const unreadMail = parseInt(jQuery("span[title*='Inbox'] + div > span").first().text(), 10);`

To:
`const unreadMail = parseInt(jQuery("div[title*='Inbox'] > span").last().text(), 10);`

I expect that Microsoft changed their UI since this recipe was developed.

**Comment by vantezzen** [comment]
This is a problem in the recipe itself (https://github.com/adambirds/recipe-office365-owa) not the repository. It looks like the original recipe is not maintained anymore but could you please check if the fork at https://github.com/nonAlgebraic/recipe-office365-owa is working? If yes, then we will simply switch to that.

**Comment by vantezzen** [comment]
@sparker2000 Any updates on this? I don't use Office 365 OWA so I cannot test the recipe I linked.

**Comment by sparker2000** [comment]
@kytwb Badge notifications are showing up for https://github.com/nonAlgebraic/recipe-office365-owa

**Comment by vantezzen** [comment]
Updated via f6353a4. The new recipe will be shipped with the next release.

**Comment by valmar** [comment]
It is still not working for me, even with the new recipe. Additionally, desktop notifications are not shown (only for the Office 365 service)

Actually, if you look at the Outlook settings, the Desktop Notifications option is not even available, while it is in the browser

Thank you for Ferdi, it's great software
