### ISSUE TITLE
Update google-chat recipe

### ISSUE THREAD

**Issue by ilopmar** [getferdi/recipes#35]
I've just discovered this project and I've switched to it instantaneously. I've been using Franz a long time but I'm tired of not being updated anymore.

I use hangouts-chat and there are two pending PRs that work but haven't been merged since a long time: https://github.com/meetfranz/recipe-hangoutschat/pulls. I forked that repo, merged the PRs and I'm using the updated recipe since them. It would be great if you can apply those PRs and release a new version of the recipe so we don't need to use custom ones and everyone can benefit from it.

It also would be great if you can fix the pending issue https://github.com/meetfranz/recipe-hangoutschat/issues

Thanks :)

**Comment by vantezzen** [comment]
I just pulled your PR into this repository - the new recipe will be shipped via the next version of Ferdi.
Unfortunately I can't help you with fixing the pending issue you mentioned but we'll be happy to merge a fix to the issue into our repository once its developed.

**Comment by ilopmar** [comment]
Thank you very much for the quick reply. I'll monitor the official repo and if someone submits a fix I'll let you know so you can pull the fixes.
