### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by SckyzO** [getferdi/recipes#355]
Name of the service (e.g. WhatsApp): Circuit
URL of the service (e.g. whatsapp.com): https://eu.yourcircuit.com/

GitHub URL to a recipe : https://github.com/circuit or https://circuit.github.io/

Features you want implemented (optional):

-

**Comment by simonszu** [comment]
Check https://github.com/getferdi/recipes/commit/02b108d4a6c684034b003b94d0979fee03f6b31a
I have implemented it. However there is a small bug in the notification badge.
