### ISSUE TITLE
Yahoo Mail

### ISSUE THREAD

**Issue by iamaayushp** [getferdi/recipes#375]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by Nokia808** [comment]
@aayushp26 
Kindly, close this because Yahoo mail already added to Ferdi, but still in master branch only & you have to wait till next release of Ferdi.
