### ISSUE TITLE
NextCloud/OwnCloud Support

### ISSUE THREAD

**Issue by rbajba** [getferdi/recipes#384]
NextCloud + OwnCloud are open source projects that offer a webdav connection to the following services:

- folders (online Drive)
- email
- Calendar
- Talk+Circles (online chat)
- Deck (Kanban board)
- Password (.KDBX encrypted vault cloud storage and client to open password files)
- Collabora (cloud based Libre/Open Office)
Would be great to be able to add the NextCloud service here.

**Comment by vantezzen** [comment]
Ferdi already has these Nextcloud services implemented - they will be available in the next update:

<img width="203" alt="Screenshot 2020-12-13 at 12 25 41" src="https://user-images.githubusercontent.com/10333196/102010443-52b82a80-3d3e-11eb-97c5-e7430bd56909.png">
