### ISSUE TITLE
Signal to Ferdi

### ISSUE THREAD

**Issue by Juhani-I** [getferdi/recipes#387]
Ferdi is missing the Signal. Signal has at least desktop version that is available in the Chrome web store.

**Comment by vantezzen** [comment]
Duplicate of:
getferdi/ferdi#444
getferdi/ferdi#342
getferdi/recipes#225
getferdi/recipes#200
getferdi/recipes#185
getferdi/recipes#159
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.
