### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by netanel0909** [getferdi/recipes#391]
Name of the service (e.g. WhatsApp): 
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vantezzen** [comment]
Duplicate of #205. Unfortunately, we can't add Spotify as the service requires a Widevine DRM Certificate which is only given to large corporations like Google or Microsoft.

**Comment by netanel0909** [comment]
Thanks anyway 😉
