### ISSUE TITLE
HEY Email

### ISSUE THREAD

**Issue by billchase2** [getferdi/recipes#393]
Name of the service (e.g. WhatsApp): HEY Email
URL of the service (e.g. whatsapp.com): http://www.hey.com

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- Proper dark mode, like both the HEY website and app provide. When adding HEY as a custom service, it does not display properly when dark mode is active.

**Comment by vantezzen** [comment]
Duplicate of #220
