### ISSUE TITLE
Can't start Inbox by Gmail 

### ISSUE THREAD

**Issue by micmeier** [getferdi/recipes#395]
**Describe the bug**
While selecting a new service,Clicking Inbox by Gmail do nothing and the panel just blink.

**To Reproduce**
1. Go to Settings
2. Click on Available Services
2. Click on Inbox by Gmail

**Expected behavior**
A new window where user can see the settings of the new service should come out

**Desktop (please complete the following information):**
 - OS: Windows Application
 - Version 5.5.0

**Comment by PnsDev** [comment]
Inbox by Gmail has been officially shut down for some time now (hence why the service will not start).

**Comment by kytwb** [comment]
Removed via https://github.com/getferdi/recipes/issues/50.
I recommend updating to a more recent of Ferdi: https://github.com/getferdi/ferdi/releases.
