### ISSUE TITLE
<SERVICE>

### ISSUE THREAD

**Issue by tbolle99** [getferdi/recipes#396]
Name of the service (e.g. WhatsApp): Line messaging app (Line is a popular messaging app in several Asian countries, and used almost exclusively in Japan and Taiwan.)
URL of the service (e.g. whatsapp.com):  https://line.me

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- full range of messaging features, eg. read and respond to messages, notifications, etc.

**Comment by vantezzen** [comment]
Line doesn't seem to offer a web app - only web extension - thus we can't add it to Ferdi, sorry.
