### ISSUE TITLE
Asana

### ISSUE THREAD

**Issue by KrisBataican** [getferdi/recipes#40]
Name of the service (e.g. WhatsApp): Asana
URL of the service (e.g. whatsapp.com): Asana.com 

GitHub URL to a recipe : https://github.com/KrisBataican/Asana-Addition.git

Features you want implemented (optional):

-

**Comment by vantezzen** [comment]
It looks like the recipe you linked is invalid. It contains the following errors:
- The recipe contains unneeded files (gulpfile.js, bowser.json, yarn.lock)
- The index.js file doesn't contain the right code
- The index.js file links to modules in the `lib/` folder which doesn't exist
- Your README.md looks to have nothing to do with the recipe?
- Your recipe does not contain an `icon.svg` and an `icon.png`
- Your `package.json` does not contain a recipe id and a Ferdi config

I'd suggest that we use https://github.com/meqabayt/franz-recipe-asana instead if that recipe is still up-to-date and working.
