### ISSUE TITLE
Could not validate https://news.google.com as Custom Website

### ISSUE THREAD

**Issue by DBecker7** [getferdi/recipes#402]
**Describe the bug**
When creating a custom website for http://news.google.com, it says "Could not validate Custom Website Server".

**To Reproduce**
1. Select Custom Website Service
2. Enter https://news.google.com as Custom server
3. Save service

**Expected behavior**
Tab for google news

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 5.5.0

**Comment by niutech** [comment]
I have the same issue, reported here: https://github.com/getferdi/ferdi/issues/276

**Comment by vraravam** [comment]
@DBecker7 @niutech - please upgrade Ferdi to the latest. I am running the beta that we released earlier this morning, and this is what I see:
<img width="1119" alt="Screenshot 2021-08-24 at 2 34 50 PM" src="https://user-images.githubusercontent.com/69629/130589441-4f895400-e5ea-4da5-ab44-df01778f1082.png">

No issues with adding `http://news.google.com` as the service url in a custom service within Ferdi 5.6.1-beta.2. You can find the beta [here](https://github.com/getferdi/ferdi/releases)

**Comment by vraravam** [comment]
Please close the bug once you can confirm that this is working.

**Comment by niutech** [comment]
I was using Ferdi 5.6.0, but now I've made Google News recipe (#613) and it is working fine.

**Comment by vraravam** [comment]
Closing since the recipe was merged a couple of days ago and I am using it without any issues.
