### ISSUE TITLE
<SERVICE>

### ISSUE THREAD

**Issue by rolbru** [getferdi/recipes#414]
Name of the service (e.g. WhatsApp): Signal (Messenger)
URL of the service (e.g. whatsapp.com): https://signal.org/de/

**Comment by S0obi** [comment]
Duplicate with https://github.com/getferdi/recipes/issues/407

**Comment by rolbru** [comment]
see https://github.com/getferdi/ferdi/issues/1155

**Comment by vraravam** [comment]
Duplicate of #18
