### ISSUE TITLE
Mastodon service cannot use custom URL

### ISSUE THREAD

**Issue by PeterCxy** [getferdi/recipes#42]
In the recipe for Mastodon (https://github.com/getferdi/recipes/blob/master/uncompressed/mastodon/package.json) the `hasCustomUrl` option was not set. The included option was a typo (I believe) that mistakenly made it `customURL`. This makes it impossible to specify a custom URL when adding Mastodon service.

Tried locally replacing `customURL` with `hasCustomUrl` and it worked.

**Comment by vantezzen** [comment]
Thank you for the report. I just fixed this problem via efaf789 - the fix should be shipped with the next version of Ferdi.
