### ISSUE TITLE
Tutanota and many other services are missing in ferdi

### ISSUE THREAD

**Issue by 0verreach3r** [getferdi/recipes#423]
I can succesfully install many services, but I can't with others, like tutanota.

![Screenshot_20210124_193925](https://user-images.githubusercontent.com/41922110/105640009-e9b6ed00-5e7b-11eb-9ca2-6ba40afcd14c.png)

As you can see here, this serivce is listed as available here.

But when I try to install it
![Screenshot_20210124_194015](https://user-images.githubusercontent.com/41922110/105640028-05ba8e80-5e7c-11eb-89a1-e28f1cae1c99.png)

It looks like it doesn't exist. I checked on the github page and it's present in the recipes list, and as I can see, many other packages are listed as installable services, but aren't present in Ferdi. (I'd say that a good ~15% of packages is missing)

**Comment by Kr4k3n02** [comment]
OK the problem is not present in the beta version 5.6.0-beta.5

**Comment by Kr4k3n02** [comment]
Updating and renewing the appimage didn't work so well. Tutanota still uninstallable.

**Comment by vraravam** [comment]
@0verreach3r - please try with the latest ferdi that was released yesterday (5.6.1). I'm able to see tutanota when I do a search.
<img width="639" alt="Screenshot 2021-09-12 at 6 51 22 AM" src="https://user-images.githubusercontent.com/69629/132967545-003c5fff-ebab-42ee-a218-ecc49cbb8c34.png">
