### ISSUE TITLE
Moodle

### ISSUE THREAD

**Issue by juekul** [getferdi/recipes#425]
Name of the service (e.g. WhatsApp): mebis
URL of the service (e.g. whatsapp.com):https://www.mebis.bayern.de/

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@juekul - since I do not use this service, it will be hard for me to implement the unread messages count, etc. Please use the code generator to create the basic shell and then implement any customizations (eg unread message counts/badges, etc).

**Comment by vantezzen** [comment]
I would take this up as I use Moodle for university a lot - some customziations like unread count might be difficult due to theming tho.
