### ISSUE TITLE
Could Tumblr be added? IN principle, this and other blogging sites would fit the concept, I think? 

### ISSUE THREAD

**Issue by AndySymons** [getferdi/recipes#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vantezzen** [comment]
You can already add tumblr and other blogging services by using the "Custom website" service. This should support all features of tumblr except displaying the number of notifications in Ferdi's sidebar.

**Comment by AndySymons** [comment]
Yes, but I need a 'Service Recipe'. Where do I get that?

**Comment by vantezzen** [comment]
You don't need a recipe for a custom website. In Ferdi, simply click on the "add service" button and add "custom website"

**Comment by AndySymons** [comment]
Ah! I see. "Custom Website" rather than "Custom Services". (You have to press "see all services" to see it). I confirm that I easily and successfully added both Tumblr and Wordpress this way. Of course, Ferdi does not pick up the logos, but it is easy to google the relevant image and add it as a custom logo. Cheers!
