### ISSUE TITLE
Infomaniak Mail

### ISSUE THREAD

**Issue by Jipem** [getferdi/recipes#450]
Name of the service : Infomaniak Mail
URL of the service : https://mail.infomaniak.com

Features you want implemented (optional):
- Notification support

**Comment by vraravam** [comment]
Looks like you might be on an older version of Ferdi (<= 5.5.x). Could you please upgrade to the latest nightlies found [here](https://github.com/vraravam/nightlies/releases) - this service is already present and supported.
