### ISSUE TITLE
Bitbucket service is missing

### ISSUE THREAD

**Issue by dreamblader** [getferdi/recipes#455]
**Describe the bug**
In the title

**To Reproduce**
1. Go to "Add service"
2. Type 'bit'
3. See that only Habitica appears

**Expected behavior**
Bitbucket service should appear

**Desktop (please complete the following information):**
 - OS: Pop! OS 20.10
 - Browser Firefox
 - Version : 5.5.0

**Comment by vraravam** [comment]
Please upgrade to the latest nightlies from [here](https://github.com/vraravam/nightlies/releases) - bitbucket is already present.
