### ISSUE TITLE
viber

### ISSUE THREAD

**Issue by jedmallen** [getferdi/recipes#456]
Name of the service (e.g. WhatsApp):  Viber
URL of the service (e.g. whatsapp.com): https://www.viber.com/

GitHub URL to a recipe :Not sure if this qualifies as a recipe - https://github.com/ned-kelly/viber-franz

Features you want implemented (optional):

-

**Comment by 7system7** [comment]
Sadly, it is not working.

**Comment by vraravam** [comment]
According to [this](https://bestappsbuzz.com/viber/viber-for-chrome-browser/) - it looks like you'll still need to install the viber app on your desktop - before this plugin can work. Not sure if we will be able to support viber from ferdi without such a dependency.

**Comment by vraravam** [comment]
Closing since we do not have support for extensions yet.
