### ISSUE TITLE
BIP Service

### ISSUE THREAD

**Issue by erturkvarol** [getferdi/recipes#461]
Name of the service (e.g. BIP Service): 
URL of the service (e.g. https://web.bip.com/):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
This is already present in Ferdi. If you are on an older version (<= 5.5.x) of Ferdi, please upgrade to the latest nightlies found [here](https://github.com/vraravam/nightlies/releases).

**Comment by erturkvarol** [comment]
Thank you very much for your reply. However, the receipt couldn't load the authentication & authorization page of BIP service.
You may need to check it, the square code on the page could not be loaded.

**Comment by vraravam** [comment]
@erturkvarol - I'm sorry, im not going to signup for a service that I dont use just to test this out. Could you please post screenshots, and other information that can help in debugging?
