### ISSUE TITLE
matrix.org recipe

### ISSUE THREAD

**Issue by francescovolpini** [getferdi/recipes#465]
Name of the service (Matrix, Element etc..): 
URL of the service (e.g. matrix.org):

GitHub URL to a recipe : https://github.com/matrix-org

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@francescovolpini - for a recipe request, please follow the documentation to create a recipe and submit a PR.

**Comment by vraravam** [comment]
btw, we already have support for element (which is a [client for matrix](https://matrix.org/docs/projects/try-matrix-now)) built-in into Ferdi.
