### ISSUE TITLE
Custom icon doesn't work

### ISSUE THREAD

**Issue by sinattieng** [getferdi/recipes#467]
**Describe the bug**

The functionality "custom icons" not work, indeed after having added one, the preview works but the ui doesn't show it (black box instend of it)

**To Reproduce**
Add a custom icon.
Check the lateral menu.

**Comment by dpanter** [comment]
Custom icons seem to work for me on Debian sid, using transparent PNG files.

**Comment by vraravam** [comment]
Unable to reproduce without more information on what OS, what version of Ferdi, the specific custom icon that you are using, etc. Closing the issue for now.
