### ISSUE TITLE
Slite not available as a service

### ISSUE THREAD

**Issue by antaflu** [getferdi/recipes#468]
**Describe the bug**

**To Reproduce**
1. Go to 'Avaiable services'
2. Search for 'Slite'
3. Nothing shows up

**Expected behavior**
I expected for Slite to sow up. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Big Sure 11.1]
 - Version [5.5.0]

**Additional context**
GetFerdi.com states that Slite is available as a service.

**Comment by vraravam** [comment]
Unable to reproduce in Ferdi 5.6.1 that was released yesterday. Please upgrade and try it out again.
