### ISSUE TITLE
Bug google drive

### ISSUE THREAD

**Issue by AlexOrdaya** [getferdi/recipes#469]
**Describe the bug**
the google drive session is not maintained

**To Reproduce**

1.Login Google Drive.

2.Enter credentials.

3.Open the google drive screen.

4.Does not maintain the session to be able to access the information.

**Expected behavior**
you should keep the session to later review the data.

**Screenshots**
[https://ibb.co/d7DLfXd](url)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by dpanter** [comment]
Confirmed same behavior on Debian sid (using .deb package)

**Comment by AlexOrdaya** [comment]
yes, in strange behavior, i also used google drive package

**Comment by dragonking91** [comment]
My ferdi has a new issue, cannot login, it transfer to default browser and open google drive website

Screenshot: https://2.pik.vn/2021642326e4-fa2b-461e-9e98-5437774f92ea.png

OS: MacOS Bigsur 11.5.1
Version of Ferdi: Version: 5.6.0, Electron: 13.1.7, Chrome: 91.0.4472.124, Node.js: 14.16.0, Platform: macOS Big Sur, Arch: x64
Version of the service-recipe: lastest

**Comment by vraravam** [comment]
@dragonking91 - this is a known issue. The workaround is that you have to right-click on the link on the top, and select "Open in Ferdi" - this will then take you into the google drive page. closing this issue.
