### ISSUE TITLE
Google Hangouts service does not load anymore

### ISSUE THREAD

**Issue by wiggisser** [getferdi/recipes#471]
**Describe the bug**

The google hangouts recipie does not load anymore. When you are still logged in it presents you with the start screen "Hello ...." but does not load the chat list.

I tried to remove and readd the service. After a successful login it is stuck in a reload loop. Ie if I open the devtools for the service, the page completely reloads every one or two seconds.

This issue is also created in the ferdi repository ... https://github.com/getferdi/ferdi/issues/1276

**To Reproduce**

- While Hangouts is still logged in 

  - Open ferdi and switch to a hangouts service.

- Remove Hangouts service
- Add hangouts service
- Login with credentials

**Expected behavior**

It should display a list of recent chats and let the user select one or more of them to chat.

**Screenshots**

See linked issue in the ferdi repository. 

**Desktop (please complete the following information):**

 ![image](https://user-images.githubusercontent.com/3647678/114718200-0f92b600-9d36-11eb-8128-85c6acf91715.png)

**Comment by wiggisser** [comment]
If it helps: I opened the developertools for the hangouts recipie and I see the following request 

- https://accounts.google.com/CheckCookie?hl=de&checkedDomains=youtube&checkConnection=youtube%3A177%3A1&pstMsg=1&chtml=LoginDoneHtml&service=talk&continue=https%3A%2F%2Fhangouts.google.com%2Fwebchat%2Fstart&gidl=EgIIAA 
   
   This one returns with 200

- https://accounts.youtube.com/accounts/SetSID

   This one shows up as cancelled

**Comment by wiggisser** [comment]
OK, now after having restarted ferdi as a whole (with letting the broken hangouts service active) hangouts does not constantly reload anymore, but I'm still stuck at the welcome screen without a chat list

**Comment by mastercko** [comment]
I have this exact issue. Ended up switching to Hangouts Chat (since Google Chat is now available to standard gmail accounts).

**Comment by vraravam** [comment]
As stated in the previous comment and [here](https://support.google.com/a/users/answer/9310166?hl=en), we will no longer be able to support *hangouts chat*. Please convert to using the *google chat* service for enhanced functionality.
