### ISSUE TITLE
Rename Riot to Element

### ISSUE THREAD

**Issue by RyuKurisu** [getferdi/recipes#475]
**Describe the bug**
Riot should be named Element, because of the name change on July 15th, 2020 [It's FOSS coverage of the name change](https://itsfoss.com/riot-to-element/)

**To Reproduce**
1. Go to 'Add new service'
2. Search for 'Element'
3. See error 'Sorry, but no service matched your search term.'

**Expected behavior**
List Element, or in the worst case at least Riot.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Ferdi: 5.5.0 (x64)
 - Electron: 8.2.3
 - Node.js: v12.13.0
 - Platform: win32

**Additional context**
I think that renaming (and changing the icon to Element) of Riot should be good enough to make it work, but maybe Element should also be shown when people search for Riot.

There is also a recipe for Franz to add Element, which can be found here: https://github.com/mchassy/element (P.S. I'm not the owner of that recipe.)

**Comment by RyuKurisu** [comment]
I just saw bug #269 but apparently this still hasn't been fixed,  Even thou #235 has been pulled on July 19, which mentions waiting for the next release?

**Comment by vraravam** [comment]
yes @RyuKurisu - this will be published in the next release. In the meantime, you can upgrade to the nightlies [here](https://github.com/vraravam/nightlies/releases) if you are keen to test this and other new features. These builds are actually quite stable.
