### ISSUE TITLE
MeWe

### ISSUE THREAD

**Issue by florianhamberger** [getferdi/recipes#484]
https://github.com/Gi11i4m/recipe-mewe

Name of the service (e.g. WhatsApp): MeWe
URL of the service (e.g. whatsapp.com): https://mewe.com

GitHub URL to a recipe : https://github.com/meetfranz/recipe-mewe

Features you want implemented (optional):

- Notification support
- Chats support

**Comment by vraravam** [comment]
@florianhamberger - the github link to the recipe that you have posted above returns a "not found".
