### ISSUE TITLE
No Gitter notifications for private messages

### ISSUE THREAD

**Issue by ilopmar** [getferdi/recipes#498]
**Describe the bug**

This is a follow up on #496. After applying that fix unread messages in channels are displayed as notifications, but when you have a mention on a channel, it's not.

**To Reproduce**

Receive a mention on a Gitter channel.

**Expected behavior**

The badge with the notification should be shown

**Screenshots**

As you see I have a mention in a Gitter channel but there is no badge on the icon.

![image](https://user-images.githubusercontent.com/559192/117930887-d3d01980-b2fe-11eb-81a1-c7d69b30f344.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser N/A
 - Version Ferdi 5.5.0 manually patched with the changes from #496

**Comment by vraravam** [comment]
@ilopmar - can you please try with the latest nightly?

Also, when you say you "have patched from #496 " - I assume you mean the recipe changes?

**Comment by ilopmar** [comment]
I'm just trying with https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.15 which I think is the latest one even if it's from February 9th. I need to wait just to get a gitter mention.

> Also, when you say you "have patched from #496 " - I assume you mean the recipe changes?

Yes, I manually apply the changes in the other PR to my recipe in `~/.config/Ferdi/recipes/gitter` and reload the services.

**Comment by vraravam** [comment]
after applying the changes to the code, simply reloading the service will have no effect. You will have to quit Ferdi and restart for those changes to come into effect.
also - sorry, but, i can't test linux issues since I'm on a mac. btw - the issues that ou are reporting have somehow been fixed on the latest code (beyond Feb 9).
would you be able to build from source and check the latest code? If not, I will request one of the other contributors to provide a build for you.

**Comment by ilopmar** [comment]
No, I'm not able to build Ferdi from source code (I'm sorry but I'm not a Javascript developer so I get lost with dependencies and tools needed to do it). 
I'm more than happy to try a new nightly (or beta) version if you release a new one.

Thanks for the help :)

**Comment by ilopmar** [comment]
@vraravam I was able to build 18.nightly version locally and tested. The issue reported here about Gitter mentions still happens.

Regarding the other issue, if you are talking about https://github.com/getferdi/ferdi/issues/1395, it also happens with that nightly.

**Comment by vraravam** [comment]
@ilopmar - is this issue fixed with the latest nightly? IF so, please close.

**Comment by ilopmar** [comment]
Sorry for the delay. Yes, it's fixed now. Thanks!
