### ISSUE TITLE
Spotify on Ferdi

### ISSUE THREAD

**Issue by leoheck** [getferdi/recipes#499]
Hey guys, what do you think to bring Spotify to Ferdi?

**Comment by kris7t** [comment]
We don't ship the Chrome DRM module with Electron, so Spotify is unlikely to work (just like when you disable DRM in Firefox and try to use Spotify inside there).

Also, I think shipping Widewine DRM requires approval from Google, which we're unlikely to get.

Also, `fsck` DRM.  😀

**Comment by vantezzen** [comment]
Related: https://github.com/getferdi/ferdi/issues/671
