### ISSUE TITLE
[Recipe Request] Riot custom URL

### ISSUE THREAD

**Issue by copitz** [getferdi/recipes#5]
Name of the recipe: riot
URL of the recipe: https://github.com/SylvainCecchetto/recipe-riot
Features you want implemented (optional): Custom URL support

Hi and thank you so much for this awesome fork!

The riot recipe is missing the custom URL functionality - the original recipe is already updated for that (see also meetfranz/plugins#319)

**Comment by vantezzen** [comment]
Implemented via 190a403. I also added a short message about Riot's default URL.
