### ISSUE TITLE
<SERVICE>Netflix missing on ferdi

### ISSUE THREAD

**Issue by So-bonkers** [getferdi/recipes#515]
Name of the service (e.g. WhatsApp):
URL of the service (e.g. whatsapp.com):

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@So-bonkers - Ferdi is not a general purpose browser. The main purpose of this is for communication (like whatsapp, slack, etc). If you are really interested in a recipe for Netflix, please submit a proper PR.

**Comment by So-bonkers** [comment]
Okay, I understand.
Thank you

Regards,
So-bonkers

________________________________

**Comment by vantezzen** [comment]
Ferdi can't currently actually run Netflix as Netflix uses Widevine DRM for its rights management. As Google doesn't give out licenses for Widevine to browsers like Ferdi, we can't make it run on Ferdi.

Related: https://github.com/getferdi/ferdi/issues/671
