### ISSUE TITLE
<Cyph> is missing

### ISSUE THREAD

**Issue by edmundlaugasson** [getferdi/recipes#516]
Name of the service: [Cyph](https://www.cyph.com/)
URL of the service: https://cyph.app

Features you want implemented (optional):
- notification support
- audio, video call support
- file upload, download support
- wallet support
- PGP, GPG support

**Comment by vraravam** [comment]
@edmundlaugasson - I will not want to sign up for yet another service just to author a recipe. Could I request you to follow the steps outlined [here](https://github.com/getferdi/recipes/blob/master/docs/integration.md) and submit a pull request?

The basics are quite easy (as outlined above), but the notification (unread count) will probably only be correct if I have registered contacts who are also on cyph and we test it by sending messages back and forth.

**Comment by edmundlaugasson** [comment]
I will not learn programming, not my area. Too overwhelmed already with other duties. Looking working software. I added as custom service and at least Cyph seems to be working. Haven't tested all functionality, but so far seems working.
