### ISSUE TITLE
Google Chat: unsupported browser

### ISSUE THREAD

**Issue by edmundlaugasson** [getferdi/recipes#517]
**Describe the bug**
Google Chat gives error message: unsupported browser

**To Reproduce**
1. added custom website https://mail.google.com/chat/
2. added it as a second website (first time it worked!)
3. see error: unsupported browser

**Expected behavior**
It should open and work like first time. Regardless, how many Google Chat accounts are logged in previously.

**Screenshots**
![google-chat-unsupported-browser](https://user-images.githubusercontent.com/6355082/119062396-6186c580-b9df-11eb-818e-6150a554dd4f.jpg)
Translation:
```
Sorry! Your current browser does not support Google Chat.
List of supported browsers
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 Cinnamon, 64-bit
 - Browser internal Ferdi
 - Version 5.6.0 beta-5 (x64), AppImage version
![ferdi-version](https://user-images.githubusercontent.com/6355082/119062704-1de08b80-b9e0-11eb-95dd-4a1f928f197d.jpg)

**Additional context**
It will ask username, password, MFA (if enabled) and then says, that unsupported browser...

Debug information
`{"host":{"platform":"linux","release":"5.4.0-73-generic","screens":[{"id":4693134009201696,"bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":27,"width":2560,"height":1386},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"workAreaSize":{"width":2560,"height":1386},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.5","electron":"9.3.2","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"element","version":"1.0.2"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"gitter","version":"1.0.2"},{"id":"googlemeet","version":"1.0.4"},{"id":"skype","version":"2.1.0"},{"id":"slack","version":"1.0.16"},{}],"devRecipes":[],"services":[{"id":"caac7a1e-5611-489e-bd2a-421464f6301a","recipe":"element","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"9b91f8b2-e012-40fa-8fd1-b0a7583febd3","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"8a6cc28d-21b6-485f-b1de-c0f40b737f8b","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"ef6c5282-3097-4295-be44-09ae2f1e18be","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"854e166b-7ce7-4eaa-81f5-4f66bea84b55","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"42dd6b4d-dc37-445b-b2b5-b19331c1d9ab","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"2f8b47e9-59da-4a3d-981e-3c3fd9ab5a7d","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"1b905206-2c58-466b-b62b-ab1199015fdb","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"5bd80445-9cd8-4b3e-bfb5-a37a840a955e","recipe":"franz-custom-website","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed prop type: The prop `customWebsiteRecipe` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _temp)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _temp)\n    in _temp (created by inject-_temp-with-stores-actions)\n    in inject-_temp-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/skype.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":26766407,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/home/edmund/.config/Ferdi/Partitions/service-9b91f8b2-e012-40fa-8fd1-b0a7583febd3/Cache/44d11c4a2ba4bb43_0"},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/franz-custom-website.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/slack.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `serviceStatus` of type `number` supplied to `_class2`, expected `mobx.ObservableArray` or javascript `array`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _temp)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _temp)\n    in _temp (created by inject-_temp-with-stores-actions)\n    in inject-_temp-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/discord.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/gitter.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `status` of type `number` supplied to `_class2`, expected `mobx.ObservableArray` or javascript `array`.\n    in _class2 (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _temp)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _temp)\n    in _temp (created by inject-_temp-with-stores-actions)\n    in inject-_temp-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar.unpacked/recipes/googlemeet.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/tmp/.mount_ferdi.B8Hf4y/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]}],"workspaces":[],"windowSettings":{"width":1162,"height":867,"x":696,"y":341,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":2560,"height":1440}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":"","privateNotifications":false,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"en-US\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"]\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://tasks.google.com/embed/?origin=https%3A%2F%2Fcalendar.google.com&fullWidth=1","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

**Comment by vraravam** [comment]
Please try with the latest recipe version using this [self-help documentation](https://github.com/getferdi/ferdi/#troubleshooting-recipes-self-help). This has been known to fix the issue. Please close the issue if the above fixes it.

**Comment by edmundlaugasson** [comment]
I'm sorry, but not developer. Looking working software.

**Comment by vraravam** [comment]
Please download the latest version of the Ferdi nighly from here: https://github.com/getferdi/nightlies/releases - this has already been fixed.
