### ISSUE TITLE
Refactor verify.js and setup continuous integration

### ISSUE THREAD

**Issue by kytwb** [getferdi/recipes#52]
Right now when people are contributing to recipes, they often have to update a binary/archive file. When reviewing the pull request, we can't see the content of the archive right from the GitHub interface, so we have to verify manually that the content of the archive is the same as the uncompressed directory content. One could potentially add malicious code in the archive and try to make so reviewers overlook it (we never know, create multiple similar pull requests for different services with only one malicious one hoping the reviewer will overlook the malicious archive, making assumptions based on other non-malicious pull requests for example).

@vantezzen already created a [verify.js](https://github.com/getferdi/recipes/blob/master/scripts/verify.js), we sould refactor it a little so it run against all recipes and then setup continuous integration so we can rely on the green tick to know we don't have to verify the archive content when reviewing from the UI.

**Comment by vantezzen** [comment]
Added the new `yarn verify-all` script via 7a289d4 and removed any errors in the recipes via f4a81fe. We can now start setting up the CI.

**Comment by vantezzen** [comment]
Just set up Travis to automatically test PRs (see #58). The test will now fail if the compressed archive is not equal to the uncompressed directory.
