### ISSUE TITLE
Harvest time tracking

### ISSUE THREAD

**Issue by timpatient** [getferdi/recipes#526]
Name of the service (e.g. WhatsApp): **Harvest time tracking**
URL of the service (e.g. whatsapp.com): https://www.getharvest.com/
GitHub URL to a recipe: https://github.com/postpostpdx/harvest-franz-recipe

Features you want implemented (optional):
- Reminder to track time
- Reminder about running timers (e.g. timers that run overnight trigger a notification if you have forgotten your timer)

**Comment by vraravam** [comment]
Thanks @timpatient - I am adding this recipe into the repo.
