### ISSUE TITLE
Injecting CSS is not being accepted

### ISSUE THREAD

**Issue by codewelldesign** [getferdi/recipes#53]
I'm having an issue with my injected CSS not being accepted in my custom app. I'm starting off with something simple just to see if it works. There is a class that I would like to edit. 

My service.css file contains this: 
` .message {border: black 1px solid !important; margin-top:100px !important;} `

My webview.js file contains this:
`  
'use strict'

module.exports = Franz => {
  const getMessages = function getMessages() {
  
    let count = 0;
    let badgeCount = document.getElementsByClassName('badge ng-scope ng-binding')[0].innerText;
    count = parseInt(badgeCount, 10);

    Franz.setBadge(count);
  };
 
Franz.injectCSS(_path.default.join(__dirname, 'service.css'));

  Franz.loop(getMessages);
};
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJwb2NrZXQvd2Vidmlldy5qcyIsInNvdXJjZXNDb250ZW50IjpbXX0= ` 

And when I open my custom app in Ferdi, I look at the code in Service Developer Tools and my new style is not displaying under that class. Plus, it would be pretty obvious on the webpage if my style was accepted?

Is this the best way to start asking support for this? I'm happy to post elsewhere. Just not sure where the community is the most active.

Thanks!

Trevor

**Comment by vantezzen** [comment]
I don't know where you get the `_path.default.join` from so I'd suggest you change your webview.js to:
```JavaScript
'use strict';

const path = require('path');

module.exports = Franz => {
  const getMessages = function getMessages() {

    let count = 0;
    let badgeCount = document.getElementsByClassName('badge ng-scope ng-binding')[0].innerText;
    count = parseInt(badgeCount, 10);

    Franz.setBadge(count);
  };

  Franz.injectCSS(path.join(__dirname, 'service.css'));

  Franz.loop(getMessages);
};
```

**Comment by codewelldesign** [comment]
Thank you!! And since I'm new to the procedure for this, do I close this issue? Will people still be able to see it where it might help them as well?

**Comment by vantezzen** [comment]
I closed the issue for you. It will still be visible for everyone having the same problem.
