### ISSUE TITLE
Fix Slack unread notifications badge behaviour

### ISSUE THREAD

**Issue by briankendall** [getferdi/recipes#54]
**Describe the bug**
When a Slack service has the following settings:
"Enable notifications": enabled
"Show unread message badges": enabled
"show message badge for all new messages": disabled

...it will still erroneously increase the notification badge for every channel that has a new message, including for messages that include `@username`, `@channel`, or `@here`.

[This bug also exists in Franz](https://github.com/meetfranz/franz/issues/1712) and has not been fixed there either.

**To Reproduce**
1. Add a slack workspace to Ferdi and sign in
2. Set its notification / unread message badge settings as indicated above
3. Have another user post a regular message to the channel without any mentions
4. The icon for the slack workspace will now have a badge with "1"

**Expected behavior**
The workspace icon is badged with an unread message, but contains no number.

**Desktop:**
- OS: macOS 10.14.6
- Ferdi Version 5.4.4-beta.2.1216

**Comment by Serubin** [comment]
This is the same issue as #39

**Comment by briankendall** [comment]
I've noticed that Slack notification badges seem to be behaving correctly now. (Not 100% sure, as I haven't been paying close attention -- will do so now to confirm it's fixed.) Would I need a later version of Ferdi to test this, or will the Slack recipe get updated automatically on its own?

**Comment by kytwb** [comment]
@briankendall Right now we ship new versions of recipes with new releases. I hope we will come back to the point where we can remotely update recipes like Franz in the near future 🙏
