### ISSUE TITLE
WhatsApp recipe (and possibly others) broken after #529

### ISSUE THREAD

**Issue by stnkl** [getferdi/recipes#543]
**Describe the bug**
Whatsapp's recipe is broken after the changes to its `webview.js` in #529. The notification badge doesn't work and the `recipe.css` does not get applied anymore. Functionality can be restored by reverting the changes to `webview.js` made in f922278. Similar changes were made to Google Meet, Android Messages and LastPass. I did not test those but I expect them to be broken too.

**Expected behavior**
Notification badge number should increase when receiving a whatsapp message. Also the whatsapp UI should have 100% width/height according to the recipe stylesheet.

I am using latest nightly (5.6 nightly 57).

**Comment by vraravam** [comment]
Thanks for the heads up @stnkl - I will raise a PR to revert those changes immediately. (Not sure why, it was working before the PR was raised and tested, and now that you reported this bug, I noticed the behavior's broken). Thanks for reportring!
