### ISSUE TITLE
<GoogleChat>

### ISSUE THREAD

**Issue by putuniki** [getferdi/recipes#548]
Service for google chat.

![icon](https://user-images.githubusercontent.com/902237/121461143-dea2ca80-c9e0-11eb-8214-924275cb7cc1.png)

**Comment by putuniki** [comment]
{
  "id": "googlechat",
  "name": "Google Chat",
  "version": "1.0.5",
  "description": "Google Chat",
  "main": "index.js",
  "author": "Putu Ardi<putu.niki@gmail.com>",
  "license": "MIT",
  "config": {
    "serviceURL": "https://chat.google.com",
    "hasDirectMessages": true,
    "hasNotificationSound": true

**Comment by vraravam** [comment]
@putuniki - this already exists. Please ensure that you are on the latest builds (nightlies can be found [here](https://github.com/vraravam/nightlies/releases)
