### ISSUE TITLE
How-to refresh page every X seconds

### ISSUE THREAD

**Issue by codewelldesign** [getferdi/recipes#55]
I am looking for a way to tell the webpage to automatically refresh every X seconds in my custom recipe. Is there a way to do this?

**Comment by vantezzen** [comment]
Add the following code to the end of your `webview.js`:

```JavaScript
const seconds = 5; // Replace 5 with your X seconds
setTimeout(() => {
    window.location.reload();
}, seconds * 60);
```

**Comment by codewelldesign** [comment]
Thank you! @vantezzen! Although, I had to change it to `seconds * 1000` to make it more like real seconds. Otherwise, it reloaded right away over and over.

**Comment by vantezzen** [comment]
Oh sorry, it should have been 1000 of course - I updated by comment above for anyone searching for a solution in the future.
