### ISSUE TITLE
Feature Request - Split windows

### ISSUE THREAD

**Issue by 3d73a4a412** [getferdi/recipes#552]
Apologies if this is not appropriate, there did not seem to be a place to do feature requests.

I'd like to request/suggest the ability to "tile" or split windows. Lots of people have large monitors so being able to say see email and chat windows at the same time for some workflows is easier than switching back and forth.

The vivaldi browser does it [quite well](https://vivaldi.com/blog/view-multiple-web-pages-side-by-side-no-extensions/)

Regardless, thanks for all the great work!

**Comment by vraravam** [comment]
@3d73a4a412 - this is a good feature request, and I can see others who might benefit from this - but, could you please move this enhancement request to the main repo here: https://github.com/getferdi/ferdi

Thanks

**Comment by 3d73a4a412** [comment]
Done! Thank you!
