### ISSUE TITLE
Gitlab recipe crashes Ferdi after failing to load

### ISSUE THREAD

**Issue by hbomb79** [getferdi/recipes#556]
**Describe the bug**
Attempting to use the Gitlab recipe in Ferdi. I get a bunch of spam output in the console in Inspect Element, talking about being unable to parse the sourcemap - primarily mentioning various RxJS modules.

The Gitlab service opens, and it appears saying it's checking my browser (normal Gitlab behavior). However this stays stuck for about 30 seconds (while the console spam occurs), and then all of Ferdi completely crashes.

**To Reproduce**
1. Clone this repo
2. Copied the Gitlab recipe into $HOME/.config/Ferdi/recipes/dev
3. Activated the custom recipe in Ferdi
4. Try to open the service

**Expected behavior**
The Gitlab sign-in page should appear eventually

**Screenshots**
Stuck on this screen:
![Image of loading screen](https://i.imgur.com/ZriL2sM.png)

Advice on how to find these logs inside a log file is appreciated so I can include them here.

**Desktop (please complete the following information):**
 - OS: ArchLinux (5.12.10)
 - Ferdi (installed from AUR, `ferdi-bin 5.5.0-3`)

**Comment by vraravam** [comment]
@hbomb79 - could you please try with the latest nightlies? I am also using gitlab - and I don't see this error at all.

**Comment by hbomb79** [comment]
Uninstalled ferdi-bin and installed ferdi-git instead. Solved the problem and actually a couple other issues I was having with notification bades for messenger.com, and the tray icon not responding to clicks. Also seems I no longer need to install the recipe in `recipes/dev` as Gitlab appears as a built in service now. Very nice :)

Thanks for the suggestion @vraravam, should have tried that before creating this issue but I had it in my head that the git version would be less stable for some reason.
