### ISSUE TITLE
Telegram doesn't show notification badge after last update

### ISSUE THREAD

**Issue by ilopmar** [getferdi/recipes#557]
**Describe the bug**

This morning there was a Telegram update and they've changed the UI. Now when you have a message the badge is not displayed.

**To Reproduce**

- Use the Telegram recipe and receive a message in any channel or private conversation.
- The Telegram icon and the systray icon don't show the badge telling that there is a new message.

**Expected behavior**

Both telegram icon in the application and systray should show the badge.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser: N/A
 - Version: Ferdi 5.6.0.nightly-57

**Comment by gustavoortega** [comment]
Hello, how are you?
Let me share with you my custom code, which is working fine!

I hope you find it useful, best regards!

**Comment by mhatvan** [comment]
I don't think custom code is necessary. There is a telegram and telegram-react recipe, for me the latter works out of the box ;)

**Comment by vraravam** [comment]
This should appear in nightly v75 (a few hours from now)

**Comment by gustavoortega** [comment]
> This should appear in nightly v75 (a few hours from now)
> 
> Thanks for providing the fix @gustavoortega

You are welcome

@vraravam, i made a little improvement, supporting group's notifications now.
This is the repo url:
https://gitlab.com/gortega4/ferdi_recipes/-/blob/main/telegram/webview.js

Best!

**Comment by vraravam** [comment]
Thanks @gustavoortega - incorporated this change as well!

**Comment by ilopmar** [comment]
I've tried with nightly.81 and this is not working for me. See screenshot:

![telegram-ferdi](https://user-images.githubusercontent.com/559192/125280033-e671c980-e314-11eb-93db-14b7d91c9a62.png)

You can see that I have a pending notification but the badge is not shown neither on Ferdi nor on the systray.

**Comment by vraravam** [comment]
@ilopmar - as per the past comments, this is known to work with the `Telegram React` service/recipe - not the `Telegram` one. Please convert/change over.

**Comment by ilopmar** [comment]
@vraravam Thanks for the quick reply. I've also tried the Telegram React recipe and it doesn't work either :-(

**Comment by ilopmar** [comment]
Ok, it seems to work if I select the `K` version. With the `Z` version it doesn't work.

![image](https://user-images.githubusercontent.com/559192/125281575-ae6b8600-e316-11eb-8c1a-dff0946570f7.png)

P.S: I don't know what those K and Z versions are.

**Comment by vraravam** [comment]
Sorry - me neither. (I don't even see those options in my `telegram-react` version.)

**Comment by ilopmar** [comment]
That is the `telegram-react` and as I mentioned before the notifications doesn't work for me there. But if I use the `telegram` recipe and select the `K` version (which seems to be the same as you are using), it works:

![image](https://user-images.githubusercontent.com/559192/125283494-c2b08280-e318-11eb-8bf7-1b4dc478d586.png)

**Comment by gustavoortega** [comment]
> That is the `telegram-react` and as I mentioned before the notifications doesn't work for me there. But if I use the `telegram` recipe and select the `K` version (which seems to be the same as you are using), it works:
> 
> ![image](https://user-images.githubusercontent.com/559192/125283494-c2b08280-e318-11eb-8bf7-1b4dc478d586.png)

Yes @ilopmar, i modified the recipe to support K version.
Do you need Z version too?

Best.

**Comment by ilopmar** [comment]
@gustavoortega to be honest I'm not really sure about the differences of the versions but I think it would be good to fix the issue in all old them, Z, K and Old.
