### ISSUE TITLE
LINE

### ISSUE THREAD

**Issue by TakayaPL** [getferdi/recipes#560]
Name of the service: LINE
URL of the service: https://line.me/en/
GitHub URL to a recipe: https://github.com/line
Features : Messenger

HELLO! I love Ferdi and to be completely happy I only miss the Japanese LINE app. It's a feature-packed app, but only messenger is enough for me. Thanks, for your good job ❤

**Comment by vraravam** [comment]
hi @TakayaPL - thanks for testing ferdi.
I dont use line, and so, i can get you a basic recipe that'll work, but things like unread message count/badge, etc will not work. Is that ok?

**Comment by TakayaPL** [comment]
Yes, of course! :)
