### ISSUE TITLE
Google Chat

### ISSUE THREAD

**Issue by ssesfahani** [getferdi/recipes#569]
Name of the service (e.g. WhatsApp): Google Chat
URL of the service (e.g. whatsapp.com): https://chat.google.com

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@ssesfahani - this is already present (The service name shows up as `hangoutschat`. Please use the latest nightlies present [here](https://github.com/vraravam/nightlies/releases).
