### ISSUE TITLE
Update GitHub to count amount of notifications

### ISSUE THREAD

**Issue by kytwb** [getferdi/recipes#57]
**Is your feature request related to a problem? Please describe.**
Right now the GitHub recipe doesn't leverage notifications.

**Describe the solution you'd like**
GitHub shipped a nice notifications center (in beta) at https://github.com/notifications/beta.

<img width="838" alt="Screen Shot 2020-03-04 at 1 10 27 AM" src="https://user-images.githubusercontent.com/412895/75831862-f5f21180-5db4-11ea-974c-1b0b77a67de8.png">

@vantezzen do you think it would make sense to update the recipe to handle notifications? I think it could be useful, and we could start [turning off GitHub email notifications](https://twitter.com/arcanis/status/1234916836577288192) completely, eventually 😁 
WDYT?

**Comment by vantezzen** [comment]
Sounds like a good idea to add notification support

**Comment by FeikoJoosten** [comment]
There you go. #129

**Comment by kytwb** [comment]
@FeikoJoosten Thank you so much! 💖 Keeping this issue open so we remember to implement proper notifications count later on! 🙏

**Comment by kytwb** [comment]
Pending global availability of notifications dashboard that includes notifications count (as per screenshot in original message).

**Comment by kytwb** [comment]
Just doubled-check and both versions have the unread notifications count:

<img width="634" alt="Screen Shot 2020-04-21 at 10 52 13 PM" src="https://user-images.githubusercontent.com/412895/79922083-ccec1580-8422-11ea-91ea-f7641a2e8db1.png">
<img width="287" alt="Screen Shot 2020-04-21 at 10 52 23 PM" src="https://user-images.githubusercontent.com/412895/79922084-ceb5d900-8422-11ea-9a27-746db672fa93.png">

**Comment by kytwb** [comment]
In both case it seems the `.count` selector matches the right notification count.

**Comment by kytwb** [comment]
That would involve changing the service URL to https://github.com/notifications though. What do you think?

**Comment by FeikoJoosten** [comment]
Just wondering, what does the service URL do exactly. Is that the url that'll be opened by Ferdi? Or is it the url that's used for checking notifications?

**Comment by kytwb** [comment]
@FeikoJoosten It's the URL that is loaded when Ferdi loads the service. To check the notifications, we don't use an URL, we continuously check the current page of the service for notifications indicators in the DOM of the page (direct count in notifications center or indirect blue dot in the header in the case of GitHub).

**Comment by FeikoJoosten** [comment]
Makes sense. Would be nice in some cases to be able to have a background process to check the notifications. That would allow you to globally check the correct number of notifications. (At least in this case). But I can imagine that being a bit overkill.

**Comment by kytwb** [comment]
@FeikoJoosten In the case of GitHub, I think we could set the direct notification count as soon as it's available, and, if navigating away and only finding the indirect notifications indicator, keep displaying the direct notifications count as it wouldn't have changed anyway and would change again once you'd go back to the notifications center. Just leaving this as a note for now.
