### ISSUE TITLE
Yandex Mail

### ISSUE THREAD

**Issue by wtsiamruk** [getferdi/recipes#571]
Name of the service (e.g. WhatsApp): Yandex.Mail
URL of the service (e.g. whatsapp.com): mail.yandex.ru

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):

- Notification Support display the web interface of the mailbox

**Comment by vraravam** [comment]
@wtsiamruk - would it be possible for you to attempt and submit a PR for this recipe? I dont use yandex mail - and so will not be able to do the notification support. The rest of the recipe-creation is actually super-easy and well documented.

**Comment by wtsiamruk** [comment]
I'll try...

**Comment by vraravam** [comment]
Implemented in #685
