### ISSUE TITLE
<SERVICE>

### ISSUE THREAD

**Issue by Kazvko** [getferdi/recipes#576]
Name of the service (e.g. WhatsApp): Notion
URL of the service (e.g. whatsapp.com): https://www.notion.so/

GitHub URL to a recipe : https://github.com/LMnet/franz-recipe-notion

Features you want implemented (optional):

-

**Comment by vraravam** [comment]
@Kazvko - there is already an existing recipe for notion. Please upgrade to the latest nightlies (I suspect you are on Ferdi 5.5 - which is VERY old at this point of time).

**Comment by Kazvko** [comment]
I literally download the .deb yesterday trough getferdi.com where i can find a newer version?

**Comment by vraravam** [comment]
@Kazvko - you can find the latest nightlies from [here](http://github.com/getferdi/nightlies/releases)
