### ISSUE TITLE
Microsoft Teams doesn't work

### ISSUE THREAD

**Issue by kassemz** [getferdi/recipes#586]
**Describe the bug**
Microsoft Teams doesn't work

We're sorry—we've run into an issue. Try again

**To Reproduce**
* Steps to reproduce the behavior:
* Install Ferdi.
* Login with your login credentials.
* See the error: "We're sorry—we've run into an issue. Try again"

**Expected behavior**
To be able to use MS Teams.

**Screenshots**
![image](https://user-images.githubusercontent.com/20356702/124671682-d7f26080-de83-11eb-8108-02e20c40e8a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Ferdi
 - Version 5.5.0

**Comment by vraravam** [comment]
@kassemz - As stated in a lot of other tickets, Ferdi v5.5.0 is *very old*. We are nearing the release of v5.6 - with only a single blocker (signed builds for windows). To get this working, I would strongly suggest that you try out one of the latest nightlies from [here](http://github.com/getferdi/nightlies/releases).

Many users have reported that MS Teams is working with the latest nightlies. Closing this issue for now.

**Comment by kassemz** [comment]
I did try the nightly build and still doesn't work unfortunately. I can
login initially but then it's that error keeps happening.

**Comment by vraravam** [comment]
What is the version of Ferdi and the specific recipe that you use?
Ferdi version is in the 'About` dialog. The service version is in the Service settings screen (all the way at the bottom - so please scroll down).

**Comment by kassemz** [comment]
Thanks @vraravam and sorry for the delay. I restarted the machine and then it worked.

Here is the info in case it is useful at all:

![image](https://user-images.githubusercontent.com/20356702/126190158-d1a92bf4-d74f-44d7-ba18-c92099bccfab.png)

Microsoft Teams recipe.

**Comment by vraravam** [comment]
@kassemz - fyi, we finally released v5.6.0 - please update to the latest stable version.
