### ISSUE TITLE
Fleep

### ISSUE THREAD

**Issue by ebousse** [getferdi/recipes#588]
Name of the service (e.g. WhatsApp): Fleep
URL of the service (e.g. whatsapp.com): https://fleep.io/

It's strange because Fleep is not in the list of available services in Ferdi 5.5.0, but the Ferdi website shows it as already integrated? https://getferdi.com/services/

**Comment by ebousse** [comment]
And actually there is a recipe here already: https://github.com/getferdi/recipes/tree/1390d5718eab1607cd5839f3ac9c846df996c3aa/recipes/fleep

Any idea why then Ferdi does not show me Fleep as part of available services?

**Comment by vraravam** [comment]
<img width="910" alt="Screenshot 2021-07-09 at 5 28 45 AM" src="https://user-images.githubusercontent.com/69629/125004206-aa213d80-e076-11eb-9136-78eb20036a57.png">

I see Fleep when I search for it in the available services.

@ebousse - I think you are on an older version of Ferdi. The website is updated based on the latest commits into the codebase - and so this reflects the latest beta that was released 2 days ago. You can find the beta [here](http://github.com/getferdi/ferdi/releases).

**Comment by ebousse** [comment]
I see, thank you! Any clue when the next stable release should appear?

**Comment by vraravam** [comment]
Please follow the discussions in https://github.com/getferdi/ferdi/issues/1017
