### ISSUE TITLE
Update Instagram to use official web version

### ISSUE THREAD

**Issue by birobirobiro** [getferdi/recipes#59]
Instagram Direct (not mobile version): 

https://www.instagram.com/direct/inbox/

**Comment by tamerciaga** [comment]
I think we should postpone this implementation until Direct on Desktop is available globally. Currently, for example, it's not available in the Netherlands. You will receive `Sorry, this page isn't available.`.

For those who already want to use Direct Desktop version, you can edit the official recipe and do the following as @birobirobiro suggested here: https://github.com/getferdi/recipes/issues/1#issuecomment-596611434

**Comment by kytwb** [comment]
@tamerciaga is it available to you now?

**Comment by tamerciaga** [comment]
@kytwb yes it's available! Would be great if it's in Ferdi now.
