### ISSUE TITLE
Wrong Habitica SVG icon

### ISSUE THREAD

**Issue by tschach** [getferdi/recipes#66]
**Describe the bug**
The SVG icon of Habitica is wrong (it's actually Notion's logo). The PNG icon is correct though.

**To Reproduce**
1. https://cdn.jsdelivr.net/gh/getferdi/recipes/uncompressed/habitica/icon.svg (URL taken from https://cdn.jsdelivr.net/gh/getferdi/recipes/all.json)

**Expected behavior**
A logo that looks like the PNG version: https://cdn.jsdelivr.net/gh/getferdi/recipes/uncompressed/habitica/icon.png

**Comment by kytwb** [comment]
Thanks for catching and reporting this 🙏

**Comment by kytwb** [comment]
@tschach taking a look at the link, I realized those are the same icons? 😅 Am I missing something?

**Comment by kytwb** [comment]
Ah yes, was fixed via https://github.com/getferdi/recipes/commit/e40d75923d7e07e83ecdefaa6e1b428654681515 🙏
