### ISSUE TITLE
Viber

### ISSUE THREAD

**Issue by sirmakessis** [getferdi/recipes#67]
is there a way to include viber messages also?

**Comment by vantezzen** [comment]
It looks like Viber doesn't offer a web version so we cannot add it to Ferdi - sorry.

**Comment by DamienCasoni** [comment]
It seems that there may be a way to use Viber as a "web app" now: 

https://github.com/ned-kelly/viber-franz

**Comment by vraravam** [comment]
You will still have to run viber in a docker container - and so this is better to done as a custom service by following their instructions. We will not be in a position to support anything that is not packaged within Ferdi.
