### ISSUE TITLE
Teamleader opens customer support chat in new window

### ISSUE THREAD

**Issue by JowJoris** [getferdi/recipes#672]
**Describe the bug**
Teamleader opens customer support chat in a new window when logging in or reloading the page.

**To Reproduce**
1. When logged into Teamleader, refresh the page
2. A new window opens called 'Freshchat' with only a button in the bottom right corner. When this button is clicked, a loading circle is shown, but doesn't do anything.

**Expected behavior**
There are two options here:
1. New window won't be opened and will be ignored.
2. The button will be shown on the main page just as in a normal browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/32440632/131980010-6835b9f4-1495-41bd-8382-11fd79f84529.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  5.6.0

**Comment by vraravam** [comment]
@JowJoris - please specify the version of ferdi etc - not chrome.

Also, this service is something that I do not have a login for - and so, will be looking for external contributors to help fix the problem

**Comment by JowJoris** [comment]
@vraravam updated the version number

**Comment by JowJoris** [comment]
It fixed itself so closing this issue
