### ISSUE TITLE
OneDrive for Personal Accounts

### ISSUE THREAD

**Issue by tahayparker** [getferdi/recipes#678]
How can we add OneDrive for Personal Accounts?

**Comment by vraravam** [comment]
You can use the `Office365` service recipe and access OneDrive from the grid menu on the top left.

**Comment by tahayparker** [comment]
I don't have a Office 365 account

**Comment by vraravam** [comment]
You can use that recipe, and change the url to the one that you want to use.

**Comment by tahayparker** [comment]
Uhh.....I did not get that...I'm new to coding and scripting

**Comment by tahayparker** [comment]
Any video or a detailed post of the instructions would be helpful
Thanks :)

**Comment by vraravam** [comment]
> Uhh.....I did not get that...I'm new to coding and scripting

I meant, in Ferdi, add a new service, and the service that you need to add will be for `Office365` (search for it). Once it comes up, you can click on "Self hosted" - and then override the url in the below text box.
<img width="663" alt="Screenshot 2021-09-09 at 2 57 51 PM" src="https://user-images.githubusercontent.com/69629/132660780-1f21f538-fae9-4edf-93ea-43192ca4643e.png">

**Comment by vraravam** [comment]
If this doesn't work, i'm sorry - I dont have a personal onedrive account to be able to take more screenshots and help.

**Comment by tahayparker** [comment]
Oh that's great, it worked

**Comment by tahayparker** [comment]
Thank You!
