### ISSUE TITLE
Unsafe browser google calendar

### ISSUE THREAD

**Issue by enrij** [getferdi/recipes#71]
When using Google Calendar recipe, after inserting username & password but BEFORE 2 step verification, google webpage returns an "error" about unsafe browser

**To Reproduce**
1. Add a service for Google Calendar
2. Login using a Google Account with 2 step authentication

**Expected behavior**
Login to Google Calendar and show the agenda

**Screenshots**
![image](https://user-images.githubusercontent.com/13519234/77244999-7b7e1a00-6c1b-11ea-809e-502b44e6abc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
 - Browser Microsoft Edge (new)
 - Version 81.0.416.34 beta

**Comment by vantezzen** [comment]
Thank you for reporting this bug. We are already discussing this at https://github.com/getferdi/ferdi/issues/264
