### ISSUE TITLE
Outlook 365 icon showing notifications of all unread messages instead of only favorites

### ISSUE THREAD

**Issue by juanluisbaptiste** [getferdi/recipes#721]
**Describe the bug**
Updated to ferdi 5.6.2 and now Outlook 365 is showing the count of of all unread messages in all folders (including trash and junk folders) instead of only favorites in the unread messages notification. Before the update only inbox folder unread messages were counted for the notification indicator.

**To Reproduce**
1. Configure an Outlook 365 account
2. Install ferdi 5.6.2
3. See notifications of unread messages for all folders instead of only favorites (like only inbox folder)

**Expected behavior**
See only notifications of unread messages of only favorite folders like inbox instead of all folders (including unread messages on junk and trash)

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04

**Comment by vraravam** [comment]
@juanluisbaptiste - sorry, there have been other users who have asked for this inclusive behavior.

btw: we have converged to only support `Office 365 Outlook` as the others were just duplicates. Please confirm that this is the one you are reporting this ticket against. To corroborate, the version of the service should show as `1.4.6` in the service-settings screen (all the way at the bottom).

**Comment by juanluisbaptiste** [comment]
@vraravam , yes, it is Office 365 Outlook, version 1.4.5.

**Comment by vraravam** [comment]
This has been committed into the main branch - will appear in the next nightly (nightly 12)
