### ISSUE TITLE
Clickup: Explain "Team" setting box that is required

### ISSUE THREAD

**Issue by CptDinosaur** [getferdi/recipes#75]
**Is your feature request related to a problem? Please describe.**
The team text entry box isn't explained. It requires the team ID (a 7 digit number), that is appended to app.clickup.com/<ID> to reach the homepage. This ID isn't easily found, I found it by logging onto the website and copying it from the URL.

**Describe the solution you'd like**
Either add some explanation, or remove the team box as a required option. The base app.clickup.com URL can be used as far as I know.

**Additional context**
https://github.com/gengue/franz-recipe-clickup Franz Recipe for it. Just uses the app.clickup.com URL.

**Comment by vantezzen** [comment]
Does the recipe you linked work? If so, we can just switch to that if the current recipe doesn't work like expected.
