### ISSUE TITLE
Newly created custom service does not show up in ferdi

### ISSUE THREAD

**Issue by simonszu** [getferdi/recipes#769]
I am currently trying to create a custom service for https://www.circuit.com/ which is our work team chat. The current WIP can be found in https://github.com/simonszu/ferdi-circuit-recipe

Next step for me would be trying out the recipe, especially the webview.js. I have copied the recipe files to the recipe dev folder
![Unbenannt](https://user-images.githubusercontent.com/700707/142850208-ad3e5f89-bf3b-4ce1-8470-c5f9d00c5b28.PNG)

Nevertheless,  Ferdi is not showing any 3rd party recipe, but recommends me to add any 3rd party recipe to the folder (which is what i did). What is going wrong here?

**Comment by vraravam** [comment]
please try to put the recipe in the `recipes` directory and not the `recipes/dev` directory.

**Comment by simonszu** [comment]
I was just following the documentation
![Unbenannt](https://user-images.githubusercontent.com/700707/142862764-c2d04b7f-9530-4ffc-8681-132ece0956ba.PNG)

However, it doesnt really matter if i put it in `.../recipes/` or in `.../recipes/myrecipe` or in `.../recipes/dev` or in `.../recipes/dev/myrecipe`. It is not shown and all i get is what is shown on the screenshot.

**Comment by vraravam** [comment]
There are multiple issues in the linked GH repo:
1. [This line](https://github.com/simonszu/ferdi-circuit-recipe/blob/e96b64b7b74fbca776679f8d6d886bb14b040586/webview.js#L15) will error out
2. The `package.json` is incorrect - one of the issues in this is the `main` key

Based on what you are trying to do, I would recommend raising a PR for a new recipe as part of the Ferdi recipes repo - and maybe someone can help. Did you try running `pnpm i && pnpm run package` command against your recipe folder to verify that all the checks pass?

**Comment by vraravam** [comment]
I have verified that, when I use one of the pre-existing recipes (with the name changed sufficiently to differentiate from the original one), and I put it into *a subfolder* for the `....recipes/dev` folder - then it shows up correctly in the `Add New Service` dialog. Actually choosing it and adding it also works as expected.

This leads me to believe that your recipe is malformed (as per my previous comment) and needs to be fixed.

**Comment by simonszu** [comment]
I fixed it with trial-and-error by copying over a working recipe and replacing my stuff one-by-one. The root cause was the version number in the package.json not strictly following SEMVER, i had it in the format x.y, but it was required to be in x.y.z. Once i changed that, the recipe is shown. 
I will do some real-world checking, and submit a pull request if everything works as expected. Thanks for your help.
