### ISSUE TITLE
[Recipe Update Request] Riot icon outdated (and inconsistent)

### ISSUE THREAD

**Issue by halms** [getferdi/recipes#77]
**Describe the bug**
The icon for Riot is outdated.
Additionally, the .svg and .png versions are not consistent (.svg includes the Riot.im text, .png does not).

**To Reproduce**
Compare:
- [Currently used SVG](https://cdn.jsdelivr.net/gh/getferdi/recipes/uncompressed/riot/icon.svg)
- [Currently used PNG](https://cdn.jsdelivr.net/gh/getferdi/recipes/uncompressed/riot/icon.png)
- [Correct logo](https://github.com/vector-im/riot-web/tree/develop/res/themes/riot/img/logos)

**Expected behavior**
The recipe should include a current and consistent logo.

The situation is not super straight-forward though, as I think that the official Riot icon is not fully suitable for use as service icon, as
1. it is not square, and
2. the Riot.im text does not fit with other services.

I would therefore suggest to use an square icon that only shows the "R", simliar to the ones [used as app icons](https://github.com/vector-im/riot-web/tree/develop/res/vector-icons), but without the white border.

I have prepared such an icon by editing the current "official" .svg and converting it to a 1024x1024px .png:
- [riot-im-logo-edited.svg.gz](https://github.com/getferdi/recipes/files/4388287/riot-im-logo-edited.svg.gz)
- [riot-im-logo-edited.png](https://user-images.githubusercontent.com/7513146/77668281-7d314000-6f83-11ea-98f3-623523067055.png)

If requested, I could also go forward and create a PR, but maybe this change is simple enough to be included directly.

**Comment by vantezzen** [comment]
Thank you for creating this issue. Could you please re-upload your .svg logo uncompressed instead of in a .gz format?

**Comment by halms** [comment]
Github does not allow uploading .svg files as attachments to issues/comments.

Renaming it to .txt works though.
[riot-im-logo-edited.svg.txt](https://github.com/getferdi/recipes/files/4397116/riot-im-logo-edited.svg.txt)

If you tell me what to change besides the icons (recipe description, version, compressed recipe, ... ?), I can also prepare a pull request.
