### ISSUE TITLE
Signal App service [Recipe Request]: 

### ISSUE THREAD

**Issue by sohaibmd21** [getferdi/recipes#772]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Signa

### URL of the service

https://signal.org/en/

### Features you want implemented

Messenger

**Comment by vraravam** [comment]
@sohaibmd21 - please search for past (closed) tickets before recreating the same ticket. Though we appreciate your use of Ferdi, its quite troublesome for the handful of contributors to constantly respond to close duplicates!
