### ISSUE TITLE
Nextcloud Talk: check for star in title indicating new messages in open chat

### ISSUE THREAD

**Issue by cm-schl** [getferdi/recipes#781]
Using Nextcloud Talk in Ferdi works very well, but I'm missing one thing: when you're in a chat with someone and you minimize the window you don't get any indication that someone wrote you in the active chat. This is a Nextcloud thing because in this cases there is no Nextcloud notification generated. But in this cases the title of the website shows new messages with a star (*).

My idea would be to add something like this to the recipe of Nextcloud Talk (webview.js):

```
    if (document.title.startsWith("*")) {
      indirect++;
    }
```

This way you also get informed about new messages in the active chat.
I'm incrementing the indirect counter because this modification can't count the real number of new messages in the chat.
One drawback seems to be that you always get a indirect badge if you have disabled the Nextcloud Chat Notifications for the actual open chat. Therefore I wanted to ask the community if this modification wouldn't interfere to much with the logic of notifications.

**Comment by vraravam** [comment]
Please raise a PR with the above changes.
