### ISSUE TITLE
Confluence

### ISSUE THREAD

**Issue by Josequiloz10** [getferdi/recipes#82]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A service to Jira Service and Conlfuence service.

**Describe alternatives you've considered**
I would like to have a service like github or trello service

**Additional context**
Thank you for everything else, you're the best!

**Comment by vantezzen** [comment]
Added Jira via 006f850. Confluence doesn't have an existing, working recipe yet and I don't use it so I can't create one.

**Comment by Josequiloz10** [comment]
Hi, thank you for your response. How can i get the Jira service?.
