### ISSUE TITLE
Mastodon issue: other recipe embedded

### ISSUE THREAD

**Issue by keunes** [getferdi/recipes#83]
Installing the Mastodon recipe creates a Mastodon recipe folder as expected. However, inside that Mastodon recipe folder, a Habitica recipe folder is added also. That's a seperate service that doesn't seem to belong there.
![Schermafdruk van 2020-03-28 09-58-55](https://user-images.githubusercontent.com/11229646/77819440-2d658c80-70db-11ea-9ce9-9fadbd6fe609.png)
![Schermafdruk van 2020-03-28 09-59-02](https://user-images.githubusercontent.com/11229646/77819441-2e96b980-70db-11ea-8784-ffb48e9035d7.png)

**Desktop:**
- OS: Ubuntu 18.04.4
- Version: 5.4.3
- Recipe version: 1.1.0

**Comment by vantezzen** [comment]
This has already been fixed via f4a81fe.
