### ISSUE TITLE
Microsoft To Do

### ISSUE THREAD

**Issue by theemstra** [getferdi/recipes#84]
**Is your feature request related to a problem? Please describe.**
There's no problem, we can open the To Do feature with the Custom website.

**Describe the solution you'd like**
The Microsoft To Do app would be nice to have as a tab in Ferdi.

**Comment by keunes** [comment]
Tip: bij de instellingen kun je ook gewoon naar "Todo server" gaan en `https://todo.microsoft.com` invoeren. Als je dan todo's inschakelt kun je gewoon inloggen en verschijnt je lijst netjes aan de zijkant. Verbreed het todo-venster iets en maak het lijstmenu links klein maken (via het hamburgermenu), en het werkt perfect.

**Comment by theemstra** [comment]
Opzich werkt dit inderdaad, dank voor de tip.
Wellicht ligt het aan mijn client of setup, maar als ik Ferdi herstart, moet ik opnieuw inloggen in die frame, terwijl dit met de custom site niet het geval is.

**Comment by keunes** [comment]
Had ik eerst ook, maar heb daarna de url in mijn eerste post aangepast. Met de huidige url (van office.com) heb ik dat probleem niet meer.

**Comment by kytwb** [comment]
Recommended way to use Microsoft Todo within Ferdi:

<img width="899" alt="Screen Shot 2020-04-22 at 1 25 06 AM" src="https://user-images.githubusercontent.com/412895/79930487-23178380-8438-11ea-9dc4-3c3506307da2.png">

Closing for now 🙏

**Comment by keunes** [comment]
@kytwb Was this newly added? I couldn't select ToDo before, there (only add custom Todo server)

**Comment by kytwb** [comment]
@keunes yes, this was added by @yourcontact via https://github.com/getferdi/ferdi/pull/527 😊
