### ISSUE TITLE
Trying to use ENTER to send Instagram messages

### ISSUE THREAD

**Issue by obvionaoe** [getferdi/recipes#86]
I made a script for Instagram to get the feature requested in #1 (add a way to use ENTER) and added it to the webview.js file... it works, but I can't seem to avoid the ENTER being actually added to the textarea element :(

this is what I currently have:

```
document.addEventListener('keydown', function(e) {
    if (e.key === 'Enter') {
      let a = document.querySelectorAll('button[type=button]').length;

      ["Enviar", "Send", "Senden", "Invia", "Skicka", "Envoyer", "Verzenden", "Отправить"].includes(document.querySelectorAll('button[type=button]')[a-1].innerText) && document.querySelectorAll('button[type=button]')[a-1].click();
      
      document.querySelectorAll('textarea')[0].value = "";
    }
});
```

Any help is appreciated!

**Comment by kytwb** [comment]
Deprecated/fixing via https://github.com/getferdi/recipes/issues/59.

**Comment by kytwb** [comment]
@obvionaoe thank you for the effort in enhancing the previous recipe, but we will be going with the official web version of Instagramm Direct. Closing for now to clear visibility to other issues 🙏
