### ISSUE TITLE
Icon of Zulip server not detected

### ISSUE THREAD

**Issue by Xerus2000** [getferdi/recipes#87]
**Describe the bug**
I am pretty sure Franz was able to get the icons of a Zulip server automatically for the sidebar, but in Ferdi it stays with the default Zulip icon.

**To Reproduce**

1. Add Zulip instance that has an own icon
2. Log in
3. Restart Ferdi

**Expected behavior**
The Zulip icon changes to the server icon.

**Desktop:**

- OS: KDE Neon (based on Ubuntu)
- Ferdi Version: 5.4.4-beta.3
- Server Used: https://api.getferdi.com

Debug information: https://debug.getferdi.com/fb1e0982-7f91-4e7b-bb55-76bc3ff0b9dd

**Comment by vantezzen** [comment]
Thank you for reporting this.
I know Ferdi can use Slack icons but it has no support for Zulip icons - you can see the open feature request to add this on https://github.com/adambirds/recipe-zulip/issues/5

**Comment by Xerus2000** [comment]
oh wow, I even reported that myself, what the heck ^^ but even with the Slack icons, the support is a little inconsistent - I feel like that also has to do with workspaces
