### ISSUE TITLE
FastMail service stuck on loading

### ISSUE THREAD

**Issue by marcolussetti** [getferdi/recipes#88]
**Describe the bug**

When adding a FastMail service, it is stuck on the initial loading screen from FastMail.

**To Reproduce**

1. Go to 'Service'
2. Search for 'FastMail'
3. Click on the FastMail icon or text
4. Save service
5. Click on the new service in the left side.

**Expected behavior**

The login prompt will be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/15794684/77600109-139e2c80-6ec4-11ea-9ecd-47cc0b4db344.png)

**Desktop:**

- OS: Windows 10 1903
- Ferdi Version 5.4.3 x64

- Server Used: default one - https://api.franzinfra.com

Debug information: Only had the option to paste it, not to publish despite instructions.
<removed>

**Additional context**

Works fine in Rambox-OS/hamsket, as well as in Chrome & Firefox.

**Comment by vantezzen** [comment]
![Screenshot 2020-03-30 at 14 21 26](https://user-images.githubusercontent.com/10333196/77911837-c76f3580-7291-11ea-8b8b-32c9e1761fe8.png)

Works fine for me. Can you please open the Service Developer Tools (View > Toggle Service Developer Tools) and look at the console to see if there are any errors reported?
The "DevTools failed to parse SourceMap" and "Electron Security Warning" messages are normal and shouldn't trigger this bug.

**Comment by marcolussetti** [comment]
Report outdated, seems fine to me now.
