### ISSUE TITLE
Framateam

### ISSUE THREAD

**Issue by Romainpetit** [getferdi/recipes#90]
Name of the service : FramaTeam
URL of the service : https://framateam.org/

GitHub URL to a recipe : https://github.com/...

Features you want implemented (optional):
-  Notification support

**Comment by vantezzen** [comment]
Your issue has been marked as "no existing recipe". Normally, we add existing recipes from GitHub as those have already been tested and contain the most important features.
As this service doesn't have existing recipes on GitHub we can't add any. If you can, please develop this recipe on your own - we will then add this to the repository - or link an existing recipe.
If you do not do either we advise you to use the "Custom website" service instead as there seems to be too low of a demand to add the recipe.
No one of the core contributors here at Ferdi use this service so we cannot develop and test a recipe on our own.

**Comment by cybermoloch** [comment]
When you go to the website, it says it is a MatterMost instance. Does adding a MatterMost service with this as the Custom URL work?

**Comment by kemenaran** [comment]
Yes, adding Framateam as a custom Mattermost URL works.

IMHO this issue can be closed.

**Comment by vraravam** [comment]
Thanks for testing @kemenaran 

@Romainpetit - please confirm if this issue can be closed?

**Comment by Romainpetit** [comment]
Yes @vraravam  all good
