### ISSUE TITLE
Update Slack recipe to support new Slack update

### ISSUE THREAD

**Issue by kytwb** [getferdi/recipes#91]
I noticed a new version of Slack being rolled out in one of my Slack. I noticed because of the UI changes and the missing custom team icon.

**Team icon**
Path: `body > div.ReactModalPortal > div > div > div > div > div > div > div:nth-child(7) > div > i`
Attribute: `background-image`

The notifications logic should also be updated but I don't have any notifications there at the moment.

**Comment by FeikoJoosten** [comment]
protip. Use `/remind me *time* "random sentence"` to let Slackbot send you a notification.

**Comment by kytwb** [comment]
@FeikoJoosten Nice one! Thank you!

**Comment by kytwb** [comment]
Looks like this was already fixed via https://github.com/getferdi/recipes/pull/80, my bad. Working in Ferdi v5.5.0-gm:

<img width="342" alt="Screen Shot 2020-04-18 at 2 08 58 PM" src="https://user-images.githubusercontent.com/412895/79638615-5dee9280-817e-11ea-9408-bf67a949f582.png">
