### ISSUE TITLE
Zulip recipe is broken

### ISSUE THREAD

**Issue by timabbott** [getferdi/recipes#93]
This is the Ferdi copy of https://github.com/meetfranz/franz/issues/1777; basically, the Zulip recipe uses a CSS class that hasn't existed in some time and thus doesn't work properly (it also causes the app to constantly send JavaScript error reports, which is quite annoying).

The fix is https://github.com/adambirds/recipe-zulip/pull/6, but @adambirds seems to be inactive, so I'm wondering if there's a way we can replace that project as the recipe upstream for Ferdi?

Thanks!

**Comment by vantezzen** [comment]
Thank you for reporting this.
As Ferdi uses its own recipe repository we can replace the recipe with another one. I have now merged the changes from the PR you linked into this repository using 58d2fa5. This change will be released with the next version of Ferdi.

**Comment by timabbott** [comment]
Awesome, thanks @vantezzen!
